(function(){
  "use strict";
  const TABS=[
    {id:"home",label:"Главная"},
    {id:"savings",label:"Экономия"},
    {id:"baskets",label:"Корзины"},
    {id:"addresses",label:"Адреса"},
    {id:"settings",label:"Настройки"}
  ];
  const read=(k,f)=>{try{const v=JSON.parse(localStorage.getItem(k)||"null");return v==null?f:v}catch{return f}};
  const profile=()=>window.TDProfileBasket?TDProfileBasket.profile():{name:"Покупатель"};
  const history=()=>window.TDProfileBasket?TDProfileBasket.history():[];
  const money=v=>Math.round(Number(v)||0).toLocaleString("ru-RU")+" ₽";
  const esc=v=>String(v==null?"":v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  function stats(){const h=history();const latest=h[h.length-1]||null;const best=h.length?Math.min(...h.map(x=>Number(x.total))):null;let saved=0;for(let i=1;i<h.length;i++){const d=Number(h[i-1].total)-Number(h[i].total);if(d>0)saved+=d;}return{days:h.length,latest,best,saved};}
  function ensureCss(){if(document.getElementById("td-account-style"))return;const s=document.createElement("style");s.id="td-account-style";s.textContent=`
  .td-account{position:fixed;inset:0;z-index:300;background:#f4f1ea;display:flex;flex-direction:column;max-width:430px;margin:auto}.td-account-head{padding:14px 16px 8px;display:flex;align-items:center;gap:10px;background:rgba(244,241,234,.96);backdrop-filter:blur(16px)}.td-account-close{width:38px;height:38px;border:0;border-radius:12px;background:#fff;font-size:19px}.td-account-title{font-weight:900;font-size:18px;letter-spacing:-.03em}.td-account-sub{font-size:10px;color:#6b6458;font-weight:700}.td-account-tabs{display:flex;gap:7px;overflow:auto;padding:6px 16px 10px;scrollbar-width:none}.td-account-tabs::-webkit-scrollbar{display:none}.td-account-tab{white-space:nowrap;border:0;border-radius:999px;padding:8px 11px;background:#fff;font:800 11px Manrope,sans-serif}.td-account-tab.on{background:#161410;color:#fff}.td-account-pages{display:flex;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none;flex:1}.td-account-pages::-webkit-scrollbar{display:none}.td-account-page{min-width:100%;scroll-snap-align:start;padding:6px 16px 32px;overflow-y:auto}.td-account-hero{background:#161410;color:#fff;border-radius:24px;padding:18px}.td-account-avatar{width:54px;height:54px;border-radius:50%;background:#ffe14a;color:#161410;display:grid;place-items:center;font-size:18px;font-weight:900;margin-bottom:12px}.td-account-name{font-size:25px;font-weight:900;letter-spacing:-.04em}.td-account-status{margin-top:6px;font-size:11px;color:#cfc8bc}.td-account-login{width:100%;margin-top:13px;border:0;border-radius:14px;background:#ffe14a;padding:12px;font:900 12px Manrope,sans-serif}.td-account-card{background:#fff;border-radius:18px;padding:14px;margin-top:10px}.td-account-card h3{font-size:13px;margin-bottom:8px}.td-account-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.td-account-stat{background:#fff;border-radius:16px;padding:12px}.td-account-stat b{display:block;font-size:20px}.td-account-stat span,.td-account-muted{font-size:10px;color:#6b6458;font-weight:700}.td-account-row{display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-top:1px solid #eee8de;font-size:11px}.td-account-row:first-child{border-top:0}.td-account-pill{display:inline-block;background:#e7f6ec;color:#0f7b4a;border-radius:999px;padding:5px 8px;font-size:10px;font-weight:900}.td-account-placeholder{padding:22px 0;color:#6b6458;font-size:11px;line-height:1.5}.td-cloud-status{font-size:12px;line-height:1.5;margin:12px 0}.td-cloud-actions{display:grid;gap:8px;margin-bottom:12px}.td-cloud-actions button{border:0;border-radius:12px;background:#e7f6ec;color:#0f7b4a;padding:12px;font:800 12px Manrope,sans-serif}.td-cloud-actions button:disabled{opacity:.5}.td-account-dots{display:flex;justify-content:center;gap:5px;padding:8px}.td-account-dot{width:5px;height:5px;border-radius:50%;background:#c8c0b3}.td-account-dot.on{width:16px;border-radius:999px;background:#161410}`;document.head.appendChild(s);}
  function initials(name){return String(name||"ТД").trim().split(/\s+/).slice(0,2).map(x=>x[0]||"").join("").toUpperCase()||"ТД";}
  function pageHtml(id){const p=profile(),st=stats(),h=history().slice(-8).reverse();if(id==="home")return `<div class="td-account-hero"><div class="td-account-avatar">${esc(initials(p.name))}</div><div class="td-account-name">${esc(p.name)}</div><div class="td-account-status">Гостевой режим · данные пока на этом устройстве</div><button class="td-account-login" type="button" data-auth>Войти / создать аккаунт</button></div><div class="td-account-grid" style="margin-top:10px"><div class="td-account-stat"><b>${st.days}</b><span>дней истории</span></div><div class="td-account-stat"><b>${st.best==null?"—":money(st.best)}</b><span>лучшая корзина</span></div></div><div class="td-account-card"><h3>Облачная копия</h3><div class="td-account-muted">Сохраняй корзину перед сменой устройства. Автоматическое сохранение пока не включено.</div><p class="td-cloud-status" role="status" aria-live="polite"></p><div class="td-cloud-actions"><button type="button" data-cloud-save>Сохранить в облако</button><button type="button" data-cloud-restore>Восстановить из облака</button></div><p class="td-account-muted">Восстановление заменит текущую корзину, профиль, адрес и историю облачной копией. Сохранение пустого адреса не удаляет ранее сохранённый адрес.</p></div>`;
  if(id==="savings")return `<div class="td-account-card"><h3>Моя экономия</h3><div style="font-size:34px;font-weight:900;letter-spacing:-.05em">${money(st.saved)}</div><div class="td-account-muted">Сумма положительных снижений между сохранёнными днями. Пока локальная метрика.</div></div><div class="td-account-card"><span class="td-account-pill">История</span>${h.map(x=>`<div class="td-account-row"><span>${esc(x.date)}</span><b>${money(x.total)}</b></div>`).join("")||'<div class="td-account-placeholder">Пока нет истории.</div>'}</div>`;
  if(id==="baskets")return `<div class="td-account-card"><h3>Мои корзины</h3><div class="td-account-placeholder">Сейчас можно сохранить одну основную корзину. Сохранение и восстановление — на вкладке «Главная». Несколько наборов добавим позже.</div></div>`;
  if(id==="addresses")return `<div class="td-account-card"><h3>Адреса</h3><div class="td-account-row"><span>Текущий адрес</span><b>${esc((window.state&&state.address)||"Не задан")}</b></div><div class="td-account-placeholder">Заполненный адрес сохраняется вместе с корзиной по кнопке «Сохранить в облако».</div></div>`;
  return `<div class="td-account-card"><h3>Настройки аккаунта</h3><div class="td-account-row"><span>Уведомления о снижении цены</span><b>Скоро</b></div><div class="td-account-row"><span>Любимые магазины</span><b>Скоро</b></div><div class="td-account-row"><span>Подписка Там Дешевле Plus</span><b>Скоро</b></div><div class="td-account-placeholder">Вход — по ссылке из письма, без пароля. Выйти из аккаунта можно на вкладке «Главная». Удаление аккаунта в приложении пока недоступно.</div></div>`;}
  function open(start=0){ensureCss();document.querySelector(".td-account")?.remove();const root=document.createElement("section");root.className="td-account";root.innerHTML=`<div class="td-account-head"><button class="td-account-close" type="button">←</button><div><div class="td-account-title">Аккаунт</div><div class="td-account-sub">Свайпай между разделами</div></div></div><div class="td-account-tabs">${TABS.map((t,i)=>`<button class="td-account-tab ${i===start?"on":""}" data-tab="${i}">${t.label}</button>`).join("")}</div><div class="td-account-pages">${TABS.map(t=>`<article class="td-account-page">${pageHtml(t.id)}</article>`).join("")}</div><div class="td-account-dots">${TABS.map((_,i)=>`<i class="td-account-dot ${i===start?"on":""}"></i>`).join("")}</div>`;document.body.appendChild(root);const pages=root.querySelector(".td-account-pages"),tabs=[...root.querySelectorAll(".td-account-tab")],dots=[...root.querySelectorAll(".td-account-dot")];const set=i=>{tabs.forEach((x,j)=>x.classList.toggle("on",j===i));dots.forEach((x,j)=>x.classList.toggle("on",j===i));};root.querySelector(".td-account-close").onclick=()=>root.remove();tabs.forEach((b,i)=>b.onclick=()=>pages.scrollTo({left:pages.clientWidth*i,behavior:"smooth"}));let raf=0;pages.addEventListener("scroll",()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>set(Math.max(0,Math.min(TABS.length-1,Math.round(pages.scrollLeft/pages.clientWidth)))));});pages.scrollLeft=pages.clientWidth*start;root.querySelector("[data-auth]")?.addEventListener("click",()=>window.dispatchEvent(new CustomEvent("td:auth-requested")));window.dispatchEvent(new CustomEvent("td:account-opened"));}
  document.addEventListener("click",e=>{const b=e.target.closest&&e.target.closest(".td-profile-btn");if(!b)return;e.preventDefault();e.stopImmediatePropagation();open(0);},true);
  window.TDAccountHub={open,tabs:TABS.slice(),authContract:{event:"td:auth-requested",futureProvider:"Supabase/Auth adapter",migrationKeys:["td:profile","td:basket-history","td"]}};
})();
