(() => {
  "use strict";
  const clone=value=>JSON.parse(JSON.stringify(value||{})),uniq=v=>[...new Set((v||[]).filter(Boolean))],low=v=>String(v||"").toLowerCase().replace(/ё/g,"е"),mem=()=>window.TDBaiMemory||null,kb=()=>window.TDBaiFoodKnowledge||null;
  const PRESETS={
    economy:{title:"Экономный",blurb:"минимум лишних трат, но с нормальной основой еды",required:["eggs","buck","pasta","bread","water"],apply(base,r=this.required){const s=clone(base);s.mode="multi";s.preferences=uniq([...(s.preferences||[]),"budget"]);s.requiredProducts=uniq([...(s.requiredProducts||[]),...r]);return s},operations(base,r=this.required){const o=[{type:"SET_MODE",value:"multi"},{type:"ADD_PREFERENCE",value:"budget"}];r.forEach(id=>o.push({type:"REQUIRE",value:id}));o.push({type:"REOPTIMIZE"});return o}},
    balanced:{title:"Сбалансированный",blurb:"есть белок, основа, фрукты и нормальные сочетания",required:["chicken","eggs","bread","banana","apple","water"],apply(base,r=this.required){const s=clone(base);s.preferences=uniq([...(s.preferences||[]),"balanced"]);s.requiredProducts=uniq([...(s.requiredProducts||[]),...r]);return s},operations(base,r=this.required){const o=[{type:"ADD_PREFERENCE",value:"balanced"}];r.forEach(id=>o.push({type:"REQUIRE",value:id}));o.push({type:"REOPTIMIZE"});return o}},
    easy:{title:"Без возни",blurb:"быстрые блюда и продукты, которые требуют минимум действий",required:["dumplings","noodles","eggs","banana","water"],apply(base,r=this.required){const s=clone(base);s.cookingPreference="minimal";s.preferences=uniq([...(s.preferences||[]),"convenience"]);s.requiredProducts=uniq([...(s.requiredProducts||[]),...r]);return s},operations(base,r=this.required){const o=[{type:"SET_COOKING",value:"minimal"},{type:"ADD_PREFERENCE",value:"convenience"}];r.forEach(id=>o.push({type:"REQUIRE",value:id}));o.push({type:"REOPTIMIZE"});return o}},
    hearty:{title:"Сытный",blurb:"больше белка и плотной основы, меньше пустых перекусов",required:["chicken","eggs","buck","pasta","bread"],apply(base,r=this.required){const s=clone(base);s.preferences=uniq([...(s.preferences||[]),"hearty"]);s.requiredProducts=uniq([...(s.requiredProducts||[]),...r]);return s},operations(base,r=this.required){const o=[{type:"ADD_PREFERENCE",value:"hearty"}];r.forEach(id=>o.push({type:"REQUIRE",value:id}));o.push({type:"REOPTIMIZE"});return o}},
    healthy:{title:"Полегче",blurb:"белок, крупа и фрукты вместо случайных сладких добивок",required:["chicken","eggs","buck","apple","banana","water","cottage"],apply(base,r=this.required){const s=clone(base);s.preferences=uniq([...(s.preferences||[]),"healthy"]);s.requiredProducts=uniq([...(s.requiredProducts||[]),...r]);return s},operations(base,r=this.required){const o=[{type:"ADD_PREFERENCE",value:"healthy"}];r.forEach(id=>o.push({type:"REQUIRE",value:id}));o.push({type:"REOPTIMIZE"});return o}}
  };
  function choosePresetIds(s,text){const t=low(text),p=(s.preferences||[]).join(" "),m=mem()?.get?.()||{};if(/готовить.*(лень|не хочу)|без готовки|быстро/.test(t)||s.cookingPreference==="minimal")return["easy","economy","balanced"];if(/сытн|плотн/.test(t)||p.includes("hearty"))return["hearty","balanced","economy"];if(/полез|полегче|здоров/.test(t)||p.includes("healthy"))return["healthy","balanced","economy"];if(/дешев|эконом|бюджет/.test(t)||p.includes("budget"))return["economy","balanced","easy"];if(m.cooking==="minimal")return["easy","balanced","economy"];return["balanced","economy","easy"]}
  function score(id,s,text,plan){const t=low(text),p=(s.preferences||[]).join(" ");let n=50;if(id==="economy"&&(/дешев|эконом|бюджет/.test(t)||p.includes("budget")))n+=35;if(id==="easy"&&(/лень|без готовки|быстро/.test(t)||s.cookingPreference==="minimal"))n+=35;if(id==="hearty"&&(/сытн|плотн/.test(t)||p.includes("hearty")))n+=35;if(id==="healthy"&&(/полез|здоров|полегче/.test(t)||p.includes("healthy")))n+=35;if(id==="balanced")n+=10;if(s.budget&&plan.total<=s.budget)n+=10;if(s.budget&&plan.total>s.budget)n-=30;const c=kb()?.coverage?.((plan.products||[]).map(x=>x.id));if(c)n+=(c.score-50)*.25;return n}
  function build(state,text=""){if(!window.TDShoppingOptimizer)return{strategies:[],recommended:null};const base=clone(state),ids=choosePresetIds(base,text),strategies=[],memory=mem(),knowledge=kb();for(const id of ids){const preset=PRESETS[id],required=memory?.filterRequired?.(preset.required)||preset.required,scenario=preset.apply(base,required),best=(window.TDShoppingOptimizer.optimize(scenario)||[])[0];if(!best)continue;const productIds=(best.products||[]).map(p=>p.id).filter(Boolean),coverage=knowledge?.coverage?.(productIds)||null,meal=/(ужин|на вечер)/.test(low(text))?"dinner":/(завтрак)/.test(low(text))?"breakfast":null,recipes=knowledge?.recipesFor?.(productIds,meal)?.slice(0,2)||[];const strategy={id,title:preset.title,description:preset.blurb,total:Math.round(best.total||0),goods:Math.round(best.goods||0),stores:(best.stores||[]).length,productCount:(best.products||[]).length,unitCount:(best.products||[]).reduce((n,p)=>n+(p.quantity||1),0),productNames:(best.products||[]).slice(0,5).map(p=>p.name),productIds,operations:preset.operations(base,required),score:score(id,base,text,best),actionText:`Выбираю вариант «${preset.title}»`,foodCoverage:coverage,mealIdeas:recipes.map(r=>r.title)};const ms=memory?.scoreStrategy?.(strategy)||{delta:0,reasons:[]};strategy.score+=ms.delta||0;strategy.memoryReasons=ms.reasons||[];strategies.push(strategy)}strategies.sort((a,b)=>b.score-a.score);return{strategies,recommended:strategies[0]||null}}
  function explain(result,state){const r=result?.recommended,list=result?.strategies||[];if(!r)return"";const cheapest=[...list].sort((a,b)=>a.total-b.total)[0];let why=`Я бы выбрал «${r.title}»: ${r.description}.`;if(r.foodCoverage?.missing?.length)why+=` По составу вижу пробелы: ${r.foodCoverage.missing.join(", ")}.`;else if(r.foodCoverage)why+=" По базе еды здесь есть белок, основа и фрукты.";if(r.mealIdeas?.length)why+=` Из этого уже складывается: ${r.mealIdeas.join("; ")}.`;if(r.memoryReasons?.length)why+=` По твоим прошлым выборам: ${r.memoryReasons.join("; ")}.`;if(cheapest&&cheapest.id!==r.id&&r.total>cheapest.total)why+=` Это примерно на ${r.total-cheapest.total} ₽ дороже самого дешёвого варианта, но лучше закрывает задачу.`;if(state.budget)why+=` Ориентир — ${state.budget} ₽.`;return why}
  function afterChoice(chosen,alts,state){if(!chosen)return{text:"",suggestions:[]};const bits=[];if(chosen.mealIdeas?.length)bits.push(`из корзины уже получаются ${chosen.mealIdeas.join(" и ")}`);if(chosen.foodCoverage&&!chosen.foodCoverage.missing.length)bits.push("по базовым ролям еда не перекошена");if(chosen.memoryReasons?.length)bits.push(`это ближе к твоим привычкам: ${chosen.memoryReasons[0]}`);const suggestions=[];if(chosen.foodCoverage?.missing?.includes("protein"))suggestions.push("Добавь белка");if(chosen.foodCoverage?.missing?.includes("fruit"))suggestions.push("Добавь фруктов");if(chosen.stores>1)suggestions.push("Собери в одном магазине");if(chosen.id!=="easy")suggestions.push("Сделай без готовки");if(chosen.id!=="economy")suggestions.push("Сделай дешевле");return{text:`Что получили: ${bits.join("; ")||"корзина собрана под выбранный сценарий"}.`,suggestions:uniq(suggestions).slice(0,4)}}
  window.TDBaiPlanner={build,explain,afterChoice,presets:PRESETS};
})();