(() => {
  "use strict";
  const PRODUCTS={"молок":"milk","хлеб":"bread","куриц":"chicken","банан":"banana","масл":"oil","яйц":"eggs","греч":"buck","сметан":"sour","сахар":"sugar","макарон":"pasta","вод":"water","яблок":"apple","ветчин":"ham","пельмен":"dumplings","лапш":"noodles","вафл":"waffles","творог":"cottage"};
  const STORES={"пятероч":"pyat","пятёроч":"pyat","магнит":"magnit","перекр":"perek","лент":"lenta","дикси":"dixy","лавк":"lavka","впрок":"vprok"};
  const NUM={"один":1,"одного":1,"одну":1,"два":2,"двое":2,"двоих":2,"двух":2,"три":3,"трое":3,"троих":3,"трех":3,"четыре":4,"четверо":4,"четверых":4,"пять":5,"шесть":6,"семь":7,"восемь":8,"девять":9,"десять":10};
  const uniq=a=>[...new Set((a||[]).filter(Boolean))],low=s=>String(s||"").toLowerCase().replace(/ё/g,"е"),state=()=>window.TDShoppingState?.get?.()||{};
  const emptyGoal=()=>({task:"basket",occasion:null,people:null,days:null,budget:null,cooking:null,preferences:[],requiredProducts:[],excludedProducts:[],onlyProducts:[],quantityTargets:{},stores:[],mode:null});
  let memory={pending:null,lastIntent:"build",turns:0,goal:emptyGoal()};
  function products(text){const t=low(text),out=[];for(const [stem,id] of Object.entries(PRODUCTS)){const p=t.indexOf(stem);if(p>=0)out.push({id,pos:p,stem})}return out.sort((a,b)=>a.pos-b.pos)}
  function stores(text){const t=low(text),out=[];for(const [stem,id] of Object.entries(STORES))if(t.includes(stem))out.push(id);return uniq(out)}
  function number(v){if(!v)return null;if(/^\d+$/.test(v))return Number(v);return NUM[low(v)]||null}
  function people(text){const m=low(text).match(/(?:нас|на|для|будет)\s+(\d+|[а-я]+)\s*(?:человек|чел|персон|едок|нас)?/);return m?number(m[1]):null}
  function days(text){const m=low(text).match(/(?:на|примерно на)\s+(\d+|[а-я]+)\s*(?:день|дня|дней|суток)/);return m?number(m[1]):null}
  function budget(text){const t=low(text);let m=t.match(/(?:до|бюджет(?:ом)?|улож(?:ись|иться) в|не больше|примерно|около)\s*([\d\s.,]+)\s*(?:р|руб|₽)/);if(m)return Number(m[1].replace(/\D/g,""));m=t.match(/(?:на)\s*([\d\s.,]+)\s*(?:р|руб|₽)/);return m?Number(m[1].replace(/\D/g,"")):null}
  function relativeBudget(text,current){const t=low(text);let m=t.match(/(?:дешевле|снизь|уменьши)\s*(?:на)?\s*(\d+)\s*%/);if(m&&current)return Math.max(1,Math.round(current*(1-Number(m[1])/100)));if(/подешевле|дешевле|сэконом/.test(t)&&current)return Math.max(1,Math.round(current*.85));return null}
  const fresh=t=>/с нуля|заново|новую корзин|начнем заново/.test(t),only=t=>/\b(только|исключительно|лишь|одни|одних)\b/.test(t)||/корзин\w*\s+из\s+/.test(t),add=t=>/\b(добав|докин|еще|плюс|положи)\w*/.test(t),remove=t=>/\b(убери|удали|исключи|выкинь|без)\b/.test(t),replace=t=>/\b(замени|поменяй|вместо)\b/.test(t);
  const normalizeUnit=u=>{u=low(u);if(/^кг|килограмм/.test(u))return"kg";if(/^г$|^гр|^грамм/.test(u))return"g";if(/^мл|миллилитр/.test(u))return"ml";if(/^л$|^литр/.test(u))return"l";if(/пач|упаков/.test(u))return"pack";if(/^шт|штук/.test(u))return"pcs";return null};
  function amounts(text,ordered){const t=low(text),out=[];const n="(\\d+(?:[.,]\\d+)?)",u="(кг|килограмм(?:а|ов)?|г|гр|грамм(?:а|ов)?|л|литр(?:а|ов)?|мл|миллилитр(?:а|ов)?|пачк(?:а|и|ек)?|упаковк(?:а|и|ок)?|шт|штук(?:а|и)?)";for(const p of ordered){const stem=p.stem.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");let m=t.match(new RegExp(n+"\\s*"+u+"\\s+[^,.!?]{0,18}"+stem))||t.match(new RegExp(stem+"[^,.!?]{0,18}?"+n+"\\s*"+u));if(m){const amount=Number(String(m[1]).replace(",",".")),unit=normalizeUnit(m[2]);if(amount>0&&unit)out.push({id:p.id,amount,unit});continue}if(["eggs","banana","apple"].includes(p.id)){m=t.match(new RegExp("(\\d+)\\s+(?:шт\\.?\\s+)?[^,.!?]{0,10}"+stem));if(m&&Number(m[1])>0)out.push({id:p.id,amount:Number(m[1]),unit:"pcs"})}}return out}
  function prefs(t){const ops=[];if(/готовить\s*(не хочу|лень|не буду)|без готовки|минимум готовки|быстро и просто/.test(t))ops.push({type:"SET_COOKING",value:"minimal"});if(/сытн|плотн|наесться/.test(t))ops.push({type:"ADD_PREFERENCE",value:"hearty"});if(/перекус|пожевать/.test(t))ops.push({type:"ADD_PREFERENCE",value:"snacks"});if(/полезн|здоров|пп\b/.test(t))ops.push({type:"ADD_PREFERENCE",value:"healthy"});if(/бюджетн|эконом/.test(t))ops.push({type:"ADD_PREFERENCE",value:"budget"});if(/фрукт/.test(t))ops.push({type:"PREFER",value:"фрукты"});if(/завтрак/.test(t))ops.push({type:"ADD_PREFERENCE",value:"breakfast"});if(/ужин|на вечер/.test(t))ops.push({type:"ADD_PREFERENCE",value:"dinner"});return ops}
  function mergeGoal(ops,text=""){const t=low(text);if(/ужин|на вечер/.test(t))memory.goal.occasion="dinner";else if(/завтрак/.test(t))memory.goal.occasion="breakfast";else if(/перекус/.test(t))memory.goal.occasion="snacks";for(const o of ops||[]){if(o.type==="RESET_BASKET")memory.goal=emptyGoal();else if(o.type==="CHANGE_BUDGET")memory.goal.budget=Number(o.value)||null;else if(o.type==="SET_PEOPLE")memory.goal.people=Number(o.value)||null;else if(o.type==="SET_DURATION")memory.goal.days=Number(o.value)||null;else if(o.type==="SET_COOKING")memory.goal.cooking=o.value;else if(o.type==="ADD_PREFERENCE"||o.type==="PREFER")memory.goal.preferences=uniq([...(memory.goal.preferences||[]),String(o.value)]);else if(o.type==="REQUIRE"||o.type==="ADD_PRODUCT")memory.goal.requiredProducts=uniq([...(memory.goal.requiredProducts||[]),String(o.value)]);else if(o.type==="REMOVE_PRODUCT"){memory.goal.excludedProducts=uniq([...(memory.goal.excludedProducts||[]),String(o.value)]);delete memory.goal.quantityTargets[o.value]}else if(o.type==="SET_ONLY_PRODUCTS")memory.goal.onlyProducts=uniq(o.value||[]);else if(o.type==="SET_PRODUCT_AMOUNT"&&o.value?.id)memory.goal.quantityTargets[o.value.id]={amount:Number(o.value.amount),unit:o.value.unit};else if(o.type==="CHANGE_STORE")memory.goal.stores=uniq([...(memory.goal.stores||[]),String(o.value)]);else if(o.type==="SET_MODE")memory.goal.mode=o.value;else if(o.type==="REPLACE_PRODUCT"&&o.value){memory.goal.excludedProducts=uniq([...(memory.goal.excludedProducts||[]),String(o.value.from)]);memory.goal.requiredProducts=uniq([...(memory.goal.requiredProducts||[]),String(o.value.to)]);if(memory.goal.quantityTargets[o.value.from]&&!memory.goal.quantityTargets[o.value.to])memory.goal.quantityTargets[o.value.to]=memory.goal.quantityTargets[o.value.from];delete memory.goal.quantityTargets[o.value.from]}}}
  function dedupeOps(ops){const seen=new Set();return(ops||[]).filter(o=>{const k=o.type+":"+JSON.stringify(o.value??null);if(seen.has(k))return false;seen.add(k);return true})}
  function simpleProposal(reply,suggestions=[]){return{ok:true,provider:"bai-brain-simple",operations:[],reply,suggestions:suggestions.slice(0,3),expectsAnswer:true,goal:JSON.parse(JSON.stringify(memory.goal))}}
  async function route(raw){raw=String(raw||"").trim();if(!raw)return simpleProposal("");memory.turns++;const t=low(raw),s=state(),ordered=products(raw),ids=uniq(ordered.map(x=>x.id)),amountList=amounts(raw,ordered),shops=stores(raw),ops=[];const b=budget(raw)||relativeBudget(raw,s.budget||memory.goal.budget),p=people(raw),d=days(raw);
    if(/верни как было|отмени последнее|назад/.test(t))return{ok:true,provider:"bai-brain-simple",operations:[{type:"UNDO"}],reply:"Откатываю.",suggestions:[],goal:JSON.parse(JSON.stringify(memory.goal))};
    if(fresh(t)){ops.push({type:"RESET_BASKET"});memory.goal=emptyGoal()}
    if(b)ops.push({type:"CHANGE_BUDGET",value:b});if(p)ops.push({type:"SET_PEOPLE",value:p});if(d)ops.push({type:"SET_DURATION",value:d});for(const st of shops)ops.push({type:"CHANGE_STORE",value:st});
    if((shops.length===1&&/только|в одном магазине/.test(t))||/собери\s+в\s+одном\s+магазине|одним магазином/.test(t))ops.push({type:"SET_MODE",value:"one"});if(/нескольк.*магаз|по разным магазин|где дешевле/.test(t))ops.push({type:"SET_MODE",value:"multi"});if(/ужми до бюджета|уложи(?:сь)? в бюджет|не вылезай за бюджет/.test(t))ops.push({type:"ADD_PREFERENCE",value:"budget"});ops.push(...prefs(t));
    if(only(t)&&ids.length){ops.push({type:"SET_INTENT",value:"only"},{type:"SET_ONLY_PRODUCTS",value:ids});memory.lastIntent="only"}
    else if(replace(t)&&ordered.length>=2){ops.push({type:"SET_INTENT",value:"replace"},{type:"REPLACE_PRODUCT",value:{from:ordered[0].id,to:ordered[ordered.length-1].id}});memory.lastIntent="replace"}
    else if(remove(t)&&ids.length){ops.push({type:"SET_INTENT",value:"remove"});ids.forEach(id=>ops.push({type:"REMOVE_PRODUCT",value:id}));memory.lastIntent="remove"}
    else if(add(t)&&ids.length){ops.push({type:"SET_INTENT",value:"add"});ids.forEach(id=>ops.push({type:"ADD_PRODUCT",value:id}));memory.lastIntent="add"}
    else if(ids.length){const cont=/^(а|и|еще|тогда|ладно|ок)\b/.test(t)||Boolean(s.products?.length);if(!cont||fresh(t))ops.push({type:"CLEAR_ONLY"},{type:"SET_INTENT",value:"build"});ids.forEach(id=>ops.push({type:"REQUIRE",value:id}));memory.lastIntent=cont?"refine":"build"}
    else if(/собери|подбери|корзин|что купить|чего взять|хочу еды|нужна еда/.test(t)){ops.push({type:"CLEAR_ONLY"},{type:"SET_INTENT",value:"build"})}
    if(!remove(t))amountList.forEach(x=>{if(!ops.some(o=>(o.type==="REQUIRE"||o.type==="ADD_PRODUCT")&&o.value===x.id))ops.push({type:"REQUIRE",value:x.id});ops.push({type:"SET_PRODUCT_AMOUNT",value:x})});
    if(/не знаю что хочу|сам реши|на твой вкус|предложи сам|простой вариант/.test(t)&&!ids.length){ops.push({type:"CLEAR_ONLY"},{type:"SET_INTENT",value:"build"},{type:"ADD_PREFERENCE",value:"balanced"})}
    if(/самый дешев|максимально дешев/.test(t)){ops.push({type:"SET_MODE",value:"multi"},{type:"ADD_PREFERENCE",value:"budget"})}
    if(!ops.length)return simpleProposal("Не понял, что изменить.",["Собрать заново"]);
    if(!ops.some(o=>o.type==="REOPTIMIZE"))ops.push({type:"REOPTIMIZE"});mergeGoal(ops,t);
    let reply="Готово.";if(ops.some(o=>o.type==="REMOVE_PRODUCT"))reply="Убрал.";else if(ops.some(o=>o.type==="REPLACE_PRODUCT"))reply="Заменил.";else if(ops.some(o=>o.type==="ADD_PRODUCT"))reply="Добавил.";else if(ops.some(o=>o.type==="SET_ONLY_PRODUCTS"))reply="Оставил только это.";else if(ops.some(o=>o.type==="SET_MODE"&&o.value==="one"))reply="Собираю в одном магазине.";else if(b&&!ids.length)reply=`Бюджет ${b} ₽.`;else if(p&&!ids.length)reply=`На ${p}.`;else if(d&&!ids.length)reply=`На ${d} дн.`;else if(/не знаю что хочу|сам реши|на твой вкус|предложи сам|простой вариант/.test(t))reply="Собрал простой вариант.";else if(/самый дешев|максимально дешев/.test(t))reply="Собрал максимально дёшево.";
    return{ok:true,provider:"bai-brain-simple",operations:dedupeOps(ops),reply,suggestions:[],expectsAnswer:false,goal:JSON.parse(JSON.stringify(memory.goal))}
  }
  function reset(){memory={pending:null,lastIntent:"build",turns:0,goal:emptyGoal()}}
  window.TDBaiBrain={route,reset,status:()=>JSON.parse(JSON.stringify(memory))};
})();