(()=>{"use strict";
const K="td_bai_memory_v1",u=a=>[...new Set((a||[]).filter(Boolean))];
const blank=()=>({version:2,turns:0,preferences:[],productsLiked:[],productsAvoided:[],productSignals:{},preferenceSignals:{},cooking:null,usualBudget:null,usualPeople:null,storeMode:null,corrections:0});
let p;try{p={...blank(),...JSON.parse(localStorage.getItem(K)||"{}")}}catch{p=blank()}
p.productSignals=p.productSignals||{};p.preferenceSignals=p.preferenceSignals||{};p.version=2;
function save(){try{localStorage.setItem(K,JSON.stringify(p))}catch{}return p}
function bump(map,key,field){if(!key)return;map[key]=map[key]||{};map[key][field]=(map[key][field]||0)+1}
function learn(raw,r){p.turns++;for(const o of r?.operations||[]){if(["ADD_PREFERENCE","PREFER"].includes(o.type)){const v=String(o.value);p.preferences=u([...p.preferences,v]);bump(p.preferenceSignals,v,"chosen")}if(o.type==="SET_COOKING")p.cooking=o.value;if(o.type==="SET_PEOPLE")p.usualPeople=Number(o.value)||p.usualPeople;if(o.type==="CHANGE_BUDGET"&&Number(o.value)>0)p.usualBudget=Number(o.value);if(o.type==="SET_MODE")p.storeMode=o.value;if(["ADD_PRODUCT","REQUIRE"].includes(o.type)){const id=String(o.value);p.productsLiked=u([...p.productsLiked,id]);bump(p.productSignals,id,"added")}if(o.type==="SET_ONLY_PRODUCTS"&&Array.isArray(o.value))for(const id of o.value){p.productsLiked=u([...p.productsLiked,String(id)]);bump(p.productSignals,String(id),"added")}if(o.type==="REMOVE_PRODUCT"){const id=String(o.value);p.productsAvoided=u([...p.productsAvoided,id]);bump(p.productSignals,id,"removed")}if(o.type==="REPLACE_PRODUCT"&&o.value){const from=String(o.value.from),to=String(o.value.to);p.productsAvoided=u([...p.productsAvoided,from]);p.productsLiked=u([...p.productsLiked,to]);bump(p.productSignals,from,"removed");bump(p.productSignals,to,"added")}}
if(/не люблю|не нравится|не предлагай|не бери|больше не/.test(String(raw||"").toLowerCase()))p.corrections++;return save()}
function signal(id){return p.productSignals?.[id]||{}}
function shouldAvoid(id){const s=signal(id),removed=s.removed||0,added=s.added||0;return removed>=3&&removed>=added+2}
function avoidList(){return Object.keys(p.productSignals||{}).filter(shouldAvoid)}
function filterRequired(ids){return (ids||[]).filter(id=>!shouldAvoid(id))}
function scoreStrategy(strategy){let delta=0,reasons=[];const id=strategy?.id,ops=strategy?.operations||[],required=ops.filter(o=>o.type==="REQUIRE").map(o=>String(o.value)),avoided=required.filter(shouldAvoid);if(avoided.length){delta-=70*avoided.length;reasons.push(`не тащу ${avoided.length} товар(а), которые ты регулярно убираешь`)}const prefs=p.preferences||[];if(id==="easy"&&p.cooking==="minimal"){delta+=24;reasons.push("ты обычно выбираешь минимум готовки")}if(id==="economy"&&prefs.includes("budget")){delta+=22;reasons.push("для тебя часто важна цена")}if(id==="hearty"&&prefs.includes("hearty")){delta+=22;reasons.push("ты чаще выбираешь сытность")}if(id==="healthy"&&prefs.includes("healthy")){delta+=22;reasons.push("ты чаще выбираешь более полезный вариант")}if(p.storeMode==="one"&&Number(strategy?.stores)<=1){delta+=14;reasons.push("ты обычно предпочитаешь один магазин")}if(p.usualBudget&&strategy?.total){if(strategy.total<=p.usualBudget)delta+=8;else if(strategy.total>p.usualBudget*1.1)delta-=12}const liked=required.filter(x=>p.productsLiked.includes(x)&&!shouldAvoid(x)).length;delta+=Math.min(8,liked*2);return{delta,reasons:reasons.slice(0,2),avoided}}
function hint(){const b=[];if(p.cooking==="minimal")b.push("обычно без лишней готовки");if(p.usualPeople>1)b.push(`обычно на ${p.usualPeople}`);if(p.preferences.includes("budget"))b.push("цена важна");if(p.preferences.includes("hearty"))b.push("любишь сытнее");const n=avoidList().length;if(n)b.push(`${n} товар(а) больше не предлагаю автоматически`);return b.slice(0,3).join(", ")}
function clear(){p=blank();try{localStorage.removeItem(K)}catch{}return p}
window.TDBaiMemory={get:()=>JSON.parse(JSON.stringify(p)),learn,hint,clear,signal,shouldAvoid,avoidList,filterRequired,scoreStrategy};
import("./bai-learning-safety.js?v=20260912-safety-v1").then(()=>import("./bai-learning-loop.js?v=20260912-learning-v2")).catch(()=>{});
})();