await import("./bai-food-knowledge.js?v=20260911-food-v2").catch(e=>console.warn("[Bai Food Knowledge] load failed",e));
await Promise.all([
  import("./bai-sufficiency.js?v=20260912-sufficiency-v1"),
  import("./bai-smart-substitutions.js?v=20260912-substitutions-v1")
]).catch(e=>console.warn("[Bai Meal Support] load failed",e));
await import("./bai-meal-brain.js?v=20260912-meal-v1").catch(e=>console.warn("[Bai Meal Brain] load failed",e));
(() => {
  "use strict";
  const clone=v=>JSON.parse(JSON.stringify(v||{})),uniq=a=>[...new Set((a||[]).filter(Boolean))],low=v=>String(v||"").toLowerCase().replace(/ё/g,"е");
  const mem=()=>window.TDBaiMemory||null,food=()=>window.TDBaiFoodKnowledge||null,mealBrain=()=>window.TDBaiMealBrain||null,suff=()=>window.TDBaiSufficiency||null,subs=()=>window.TDBaiSmartSubstitutions||null;
  const PRESETS={
    economy:{title:"Экономный",blurb:"минимум лишних трат, можно разнести покупки по магазинам",required:["eggs","buck","pasta","bread","water"],apply(base,required=this.required){const s=clone(base);s.mode="multi";s.preferences=uniq([...(s.preferences||[]),"budget"]);if(s.budget)s.budget=Math.max(500,Math.round(s.budget*.78));s.requiredProducts=uniq([...(s.requiredProducts||[]),...required]);return s},operations(base,required=this.required){const ops=[{type:"SET_MODE",value:"multi"},{type:"ADD_PREFERENCE",value:"budget"}];if(base.budget)ops.unshift({type:"CHANGE_BUDGET",value:Math.max(500,Math.round(base.budget*.78))});required.forEach(id=>ops.push({type:"REQUIRE",value:id}));ops.push({type:"REOPTIMIZE"});return ops}},
    balanced:{title:"Сбалансированный",blurb:"нормальный запас еды без сильного перекоса в цену или удобство",required:["chicken","eggs","bread","banana","apple","water"],apply(base,required=this.required){const s=clone(base);s.preferences=uniq([...(s.preferences||[]),"balanced"]);s.requiredProducts=uniq([...(s.requiredProducts||[]),...required]);return s},operations(base,required=this.required){const ops=[{type:"ADD_PREFERENCE",value:"balanced"}];required.forEach(id=>ops.push({type:"REQUIRE",value:id}));ops.push({type:"REOPTIMIZE"});return ops}},
    easy:{title:"Без возни",blurb:"еда, которую можно быстро съесть или приготовить с минимумом действий",required:["dumplings","noodles","eggs","banana","water"],apply(base,required=this.required){const s=clone(base);s.cookingPreference="minimal";s.preferences=uniq([...(s.preferences||[]),"convenience"]);s.requiredProducts=uniq([...(s.requiredProducts||[]),...required]);return s},operations(base,required=this.required){const ops=[{type:"SET_COOKING",value:"minimal"},{type:"ADD_PREFERENCE",value:"convenience"}];required.forEach(id=>ops.push({type:"REQUIRE",value:id}));ops.push({type:"REOPTIMIZE"});return ops}},
    hearty:{title:"Сытный",blurb:"больше основы и плотной еды, меньше пустых перекусов",required:["chicken","eggs","buck","pasta","bread"],apply(base,required=this.required){const s=clone(base);s.preferences=uniq([...(s.preferences||[]),"hearty"]);s.requiredProducts=uniq([...(s.requiredProducts||[]),...required]);return s},operations(base,required=this.required){const ops=[{type:"ADD_PREFERENCE",value:"hearty"}];required.forEach(id=>ops.push({type:"REQUIRE",value:id}));ops.push({type:"REOPTIMIZE"});return ops}},
    healthy:{title:"Полегче",blurb:"больше обычной еды и фруктов, меньше случайных сладких добивок",required:["chicken","eggs","buck","apple","banana","water","cottage"],apply(base,required=this.required){const s=clone(base);s.preferences=uniq([...(s.preferences||[]),"healthy"]);s.requiredProducts=uniq([...(s.requiredProducts||[]),...required]);return s},operations(base,required=this.required){const ops=[{type:"ADD_PREFERENCE",value:"healthy"}];required.forEach(id=>ops.push({type:"REQUIRE",value:id}));ops.push({type:"REOPTIMIZE"});return ops}}
  };
  function mealOf(state,text){const t=low(text),p=(state.preferences||[]).join(" ");if(/завтрак/.test(t)||p.includes("breakfast"))return"breakfast";if(/перекус|к сериалу|к фильму/.test(t)||p.includes("snacks"))return"snack";if(/ужин|на вечер/.test(t)||p.includes("dinner"))return"dinner";return null}
  function fullMealJourney(state,text){const t=low(text),meal=mealOf(state,text);if(meal&&Math.max(1,Number(state.duration)||1)<=1&&!/рацион|на неделю|на \d+\s*(?:дн|дня|дней)/.test(t))return false;return Math.max(1,Number(state.duration)||1)>1||/рацион|на неделю|на \d+\s*(?:дн|дня|дней)|собери[^.!?]{0,40}(?:ед|продукт|корзин)|сам реши|реши сам/.test(t)}
  function choosePresetIds(state,text){const t=low(text),prefs=(state.preferences||[]).join(" "),profile=mem()?.get?.()||{};if(/готовить.*(лень|не хочу)|без готовки|быстро/.test(t)||state.cookingPreference==="minimal")return["easy","economy","balanced"];if(/сытн|плотн/.test(t)||prefs.includes("hearty"))return["hearty","balanced","economy"];if(/полез|полегче|здоров/.test(t)||prefs.includes("healthy"))return["healthy","balanced","economy"];if(/дешев|эконом|бюджет/.test(t)||prefs.includes("budget"))return["economy","balanced","easy"];if(profile.cooking==="minimal")return["easy","balanced","economy"];if((profile.preferences||[]).includes("hearty"))return["hearty","balanced","economy"];if((profile.preferences||[]).includes("healthy"))return["healthy","balanced","economy"];if((profile.preferences||[]).includes("budget"))return["economy","balanced","easy"];return["balanced","economy","easy"]}
  function score(id,state,text,plan){const t=low(text),prefs=(state.preferences||[]).join(" ");let n=50;if(id==="economy"&&(/дешев|эконом|бюджет/.test(t)||prefs.includes("budget")))n+=35;if(id==="easy"&&(/лень|без готовки|быстро/.test(t)||state.cookingPreference==="minimal"))n+=35;if(id==="hearty"&&(/сытн|плотн/.test(t)||prefs.includes("hearty")))n+=35;if(id==="healthy"&&(/полез|здоров|полегче/.test(t)||prefs.includes("healthy")))n+=35;if(id==="balanced")n+=10;if(state.budget&&plan.total<=state.budget)n+=10;if(state.budget&&plan.total>state.budget)n-=30;return n}
  function smartRequired(id,required,meal,state){const k=food();let out=required;if(k&&id!=="economy"&&id!=="easy")out=uniq([...required,...(k.suggestAdditions?.(required,meal)||[]).slice(0,2)]);return subs()?.repairRequired?.(out,state,{meal,preferReady:state.cookingPreference==="minimal"})?.required||out}
  function mergeTargets(state,mealPlan){const s=clone(state);s.quantityTargets={...(s.quantityTargets||{}),...(mealPlan?.quantityTargets||{})};return s}
  function mergeOperations(baseOps,mealPlan){const body=(baseOps||[]).filter(x=>x?.type!=="REOPTIMIZE"),seen=new Set(body.map(x=>`${x.type}:${JSON.stringify(x.value)}`));for(const op of mealPlan?.operations||[]){const key=`${op.type}:${JSON.stringify(op.value)}`;if(!seen.has(key)){seen.add(key);body.push(op)}}body.push({type:"REOPTIMIZE"});return body}
  function build(state,text=""){
    if(!window.TDShoppingOptimizer)return{strategies:[],recommended:null};
    const base=clone(state),ids=choosePresetIds(base,text),strategies=[],memory=mem(),meal=mealOf(base,text),k=food(),useMeals=fullMealJourney(base,text);
    for(const id of ids){const preset=PRESETS[id];let required=memory?.filterRequired?.(preset.required)||preset.required;required=smartRequired(id,required,meal,base);let scenario=preset.apply(base,required),mealPlan=null;
      if(useMeals&&mealBrain()){mealPlan=mealBrain().plan(scenario,text);required=uniq([...required,...(mealPlan.requiredProducts||[])]);required=subs()?.repairRequired?.(required,scenario,{meal,preferReady:scenario.cookingPreference==="minimal"})?.required||required;scenario=preset.apply(base,required);scenario=mergeTargets(scenario,mealPlan)}
      const plans=window.TDShoppingOptimizer.optimize(scenario)||[],best=plans[0];if(!best)continue;
      const productIds=(best.products||[]).map(p=>p.id).filter(Boolean),strategy={id,title:preset.title,description:preset.blurb,total:Math.round(best.total||0),goods:Math.round(best.goods||0),stores:(best.stores||[]).length,productCount:(best.products||[]).length,unitCount:(best.products||[]).reduce((n,p)=>n+(p.quantity||1),0),productNames:(best.products||[]).slice(0,5).map(p=>p.name),productIds,operations:mergeOperations(preset.operations(base,required),mealPlan),score:score(id,base,text,best),actionText:`Выбираю вариант «${preset.title}»`,meal,mealPlan};
      const ms=memory?.scoreStrategy?.(strategy)||{delta:0,reasons:[]};strategy.score+=ms.delta||0;strategy.memoryReasons=ms.reasons||[];strategy.memoryAvoided=ms.avoided||[];
      if(k){strategy.foodScore=k.scorePlan?.(productIds,meal)||0;strategy.foodReasons=k.explain?.(productIds,meal)||[];strategy.foodRecipes=(k.recipesFor?.(productIds,meal)||[]).slice(0,2);strategy.score+=Math.max(-12,Math.min(18,Math.round((strategy.foodScore-70)*.35)))}
      if(useMeals&&suff()){strategy.sufficiency=suff().audit(scenario,best,mealPlan);strategy.score+=Math.round((strategy.sufficiency.score-70)*.35);if(strategy.sufficiency.gaps.length)strategy.score-=Math.min(20,strategy.sufficiency.gaps.length*5)}
      if(mealPlan?.budgetPressure)strategy.score-=16;
      strategies.push(strategy)}
    strategies.sort((a,b)=>b.score-a.score);return{strategies,recommended:strategies[0]||null,meal,mealJourney:useMeals}
  }
  function explain(result,state){const r=result?.recommended,list=result?.strategies||[];if(!r)return"";const cheapest=[...list].sort((a,b)=>a.total-b.total)[0];let why=`Я бы выбрал «${r.title}»: ${r.description}.`;if(r.mealPlan){why+=` ${mealBrain()?.explain?.(r.mealPlan)||""}.`;if(r.sufficiency)why+=` По запасу: ${r.sufficiency.label} (${r.sufficiency.score}/100).`;if(r.sufficiency?.gaps?.length)why+=` Ещё вижу: ${r.sufficiency.gaps.slice(0,2).map(x=>x.label).join("; ")}.`}
    else if(r.foodReasons?.length)why+=` По составу корзины: ${r.foodReasons.slice(0,2).join("; ")}.`;
    const ready=r.foodRecipes?.find(x=>x.missing?.length===0);if(!r.mealPlan&&ready)why+=` Из неё уже складывается «${ready.title}».`;if(r.memoryReasons?.length)why+=` По твоим прошлым выборам: ${r.memoryReasons.join("; ")}.`;if(cheapest&&cheapest.id!==r.id){const d=r.total-cheapest.total;if(d>0)why+=` Он примерно на ${d} ₽ дороже самого дешёвого, но лучше попадает в задачу.`}else if(cheapest)why+=" И он же сейчас выходит самым дешёвым из нормальных вариантов.";if(state.budget)why+=` Ориентир по бюджету — ${state.budget} ₽.`;return why.replace(/\s+/g," ").trim()}
  function afterChoice(chosen,alternatives,state){if(!chosen)return{text:"",suggestions:[]};const list=Array.isArray(alternatives)?alternatives:[],cheapest=[...list].sort((a,b)=>a.total-b.total)[0],fullest=[...list].sort((a,b)=>b.unitCount-a.unitCount)[0],fewest=[...list].sort((a,b)=>a.stores-b.stores||a.total-b.total)[0],bits=[];if(cheapest&&cheapest.id!==chosen.id){const d=Math.max(0,chosen.total-cheapest.total);if(d)bits.push(`платим примерно на ${d} ₽ больше самого дешёвого варианта`)}else bits.push("по цене это один из самых аккуратных вариантов");if(fullest?.id===chosen.id)bits.push("здесь больше всего еды из показанных вариантов");if(chosen.sufficiency)bits.push(`${chosen.sufficiency.label}: ${chosen.sufficiency.score}/100`);else if(chosen.foodReasons?.length)bits.push(chosen.foodReasons[0]);const ready=chosen.foodRecipes?.find(x=>x.missing?.length===0);if(!chosen.mealPlan&&ready)bits.push(`есть готовая связка: ${ready.title}`);if(fewest&&chosen.stores>fewest.stores)bits.push(`придётся зайти в ${chosen.stores} магазина вместо ${fewest.stores}`);const total=Number(state?.currentTotal)||chosen.total||0,budget=Number(state?.budget)||0,suggestions=[];if(budget&&total>budget)suggestions.push("Ужми до бюджета");else if(budget&&total<budget*.82)suggestions.push("Добавь сытности");if(chosen.stores>1)suggestions.push("Собери в одном магазине");if(chosen.id!=="easy")suggestions.push("Сделай без готовки");if(chosen.id!=="economy")suggestions.push("Сделай дешевле");suggestions.push("Оставь так");return{text:`Что получили: ${bits.join("; ")}.`,suggestions:uniq(suggestions).slice(0,4)}}
  window.TDBaiPlanner={build,explain,afterChoice,presets:PRESETS,mealOf,fullMealJourney};
})();