(() => {
  "use strict";

  const PRODUCTS={"молок":"milk","хлеб":"bread","куриц":"chicken","банан":"banana","масл":"oil","яйц":"eggs","греч":"buck","сметан":"sour","сахар":"sugar","макарон":"pasta","вод":"water","яблок":"apple","ветчин":"ham","пельмен":"dumplings","лапш":"noodles","вафл":"waffles","творог":"cottage"};
  const STORES={"пятероч":"pyat","пятёроч":"pyat","магнит":"magnit","перекр":"perek","лент":"lenta","дикси":"dixy","лавк":"lavka","впрок":"vprok"};
  const NUM={"один":1,"одного":1,"одну":1,"два":2,"двое":2,"двоих":2,"двух":2,"три":3,"трое":3,"троих":3,"трех":3,"четыре":4,"четверо":4,"четверых":4,"пять":5,"шесть":6,"семь":7,"восемь":8,"девять":9,"десять":10};
  const uniq=a=>[...new Set((a||[]).filter(Boolean))],low=s=>String(s||"").toLowerCase().replace(/ё/g,"е"),state=()=>window.TDShoppingState?.get?.()||{};
  let memory={pending:null,lastIntent:"build",turns:0,lastSuggestions:[]};
  function products(text){const t=low(text),out=[];for(const [stem,id] of Object.entries(PRODUCTS)){const p=t.indexOf(stem);if(p>=0)out.push({id,pos:p})}return out.sort((a,b)=>a.pos-b.pos)}
  function stores(text){const t=low(text),out=[];for(const [stem,id] of Object.entries(STORES))if(t.includes(stem))out.push(id);return uniq(out)}
  function number(v){if(!v)return null;if(/^\d+$/.test(v))return Number(v);return NUM[low(v)]||null}
  function people(text){const m=low(text).match(/(?:нас|на|для|будет)\s+(\d+|[а-я]+)\s*(?:человек|чел|персон|едок|нас)?/);return m?number(m[1]):null}
  function days(text){const m=low(text).match(/(?:на|примерно на)\s+(\d+|[а-я]+)\s*(?:день|дня|дней|суток)/);return m?number(m[1]):null}
  function budget(text){const t=low(text);let m=t.match(/(?:до|бюджет(?:ом)?|улож(?:ись|иться) в|не больше|примерно|около)\s*([\d\s.,]+)\s*(?:р|руб|₽)/);if(m)return Number(m[1].replace(/\D/g,""));m=t.match(/(?:на)\s*([\d\s.,]+)\s*(?:р|руб|₽)/);return m?Number(m[1].replace(/\D/g,"")):null}
  function relativeBudget(text,current){const t=low(text);let m=t.match(/(?:дешевле|снизь|уменьши)\s*(?:на)?\s*(\d+)\s*%/);if(m&&current)return Math.max(1,Math.round(current*(1-Number(m[1])/100)));if(/подешевле|дешевле|сэконом/.test(t)&&current)return Math.max(1,Math.round(current*.85));return null}
  const yes=t=>/^(да|ага|угу|давай|ок|окей|верно|поехали)\b/.test(low(t).trim()),no=t=>/^(нет|неа|не надо|отмена)\b/.test(low(t).trim());
  const fresh=t=>/с нуля|заново|новую корзин|начн[её]м заново/.test(t),only=t=>/\b(только|исключительно|лишь|одни|одних)\b/.test(t)||/корзин\w*\s+из\s+/.test(t),add=t=>/\b(добав|докин|еще|плюс|положи)\w*/.test(t),remove=t=>/\b(убери|удали|исключи|выкинь|без)\b/.test(t),replace=t=>/\b(замени|поменяй|вместо)\b/.test(t);
  function prefs(t){const ops=[];if(/готовить\s*(не хочу|лень|не буду)|без готовки|минимум готовки|быстро и просто/.test(t))ops.push({type:"SET_COOKING",value:"minimal"});if(/сытн|плотн|наесться|пожирнее/.test(t))ops.push({type:"ADD_PREFERENCE",value:"hearty"});if(/перекус|пожевать|к сериалу|к фильму/.test(t))ops.push({type:"ADD_PREFERENCE",value:"snacks"});if(/полезн|здоров|пп\b/.test(t))ops.push({type:"ADD_PREFERENCE",value:"healthy"});if(/бюджетн|эконом/.test(t))ops.push({type:"ADD_PREFERENCE",value:"budget"});if(/фрукт/.test(t))ops.push({type:"PREFER",value:"фрукты"});if(/сладк|к чаю/.test(t))ops.push({type:"PREFER",value:"сладкое"});if(/завтрак/.test(t))ops.push({type:"ADD_PREFERENCE",value:"breakfast"});if(/ужин|на вечер/.test(t))ops.push({type:"ADD_PREFERENCE",value:"dinner"});return ops}
  function question(text,options,kind){memory.pending={kind};memory.lastSuggestions=options||[];return{ok:true,provider:"bai-brain-v2",operations:[{type:"ASK_CLARIFICATION",value:text}],reply:text,suggestions:options||[],expectsAnswer:true}}
  function proposal(text,options){memory.lastSuggestions=options||[];return{ok:true,provider:"bai-brain-v2",operations:[],reply:text,suggestions:options||[],expectsAnswer:true}}
  function resolvePending(raw){const p=memory.pending;if(!p)return null;const t=low(raw);memory.pending=null;if(p.kind==="budget"){const b=budget(raw)||number(t.trim());if(b)return{operations:[{type:"CHANGE_BUDGET",value:b},{type:"REOPTIMIZE"}],reply:`Принял ${b} ₽. Теперь могу нормально оптимизировать корзину.`,suggestions:[]};if(/без бюджета|неважно|любой/.test(t))return{operations:[{type:"REOPTIMIZE"}],reply:"Окей, жёсткий потолок не ставлю. Смотрю на разумную стоимость.",suggestions:[]}}if(p.kind==="people"){const n=people(raw)||number(t.trim());if(n)return{operations:[{type:"SET_PEOPLE",value:n},{type:"REOPTIMIZE"}],reply:`Понял, на ${n}. Пересчитываю количество.`,suggestions:[]}}if(p.kind==="style"){if(/сыт/.test(t))return{operations:[{type:"ADD_PREFERENCE",value:"hearty"},{type:"REOPTIMIZE"}],reply:"Делаю упор на сытность.",suggestions:[]};if(/перекус|снэк|снек/.test(t))return{operations:[{type:"ADD_PREFERENCE",value:"snacks"},{type:"REOPTIMIZE"}],reply:"Окей, больше удобных перекусов.",suggestions:[]};if(/полез/.test(t))return{operations:[{type:"ADD_PREFERENCE",value:"healthy"},{type:"REOPTIMIZE"}],reply:"Понял, смещаю выбор в более полезную сторону.",suggestions:[]};if(/дешев|эконом/.test(t))return{operations:[{type:"ADD_PREFERENCE",value:"budget"},{type:"REOPTIMIZE"}],reply:"Тогда приоритет — цена.",suggestions:[]}}if(p.kind==="cooking"){if(/не хочу|лень|без готовки/.test(t)||yes(raw))return{operations:[{type:"SET_COOKING",value:"minimal"},{type:"REOPTIMIZE"}],reply:"Окей, почти без готовки.",suggestions:[]};if(no(raw)||/готовить могу|нормально готовить/.test(t))return{operations:[{type:"SET_COOKING",value:"normal"},{type:"REOPTIMIZE"}],reply:"Понял, готовку не ограничиваю.",suggestions:[]}}if(no(raw))return{operations:[],reply:"Хорошо, это уточнение отменил. Продолжай.",suggestions:[]};return null}
  function advisor(raw,s){const t=low(raw),best=s.lastPlans?.[0];if(/хватит ли|нормально ли|как корзина|что скажешь|оцени/.test(t)&&best){const b=s.budget||0,total=best.total||0;if(b&&total>b)return proposal(`Сейчас корзина выше бюджета примерно на ${Math.round(total-b)} ₽. Я бы сначала ужал лишнее, а обязательное оставил.`,["Ужми цену","Покажи что убрать","Оставь как есть"]);if(b&&total<b*.72)return proposal(`Запас бюджета ещё около ${Math.round(b-total)} ₽. Можно либо оставить экономный вариант, либо усилить корзину.`,["Добавь сытности","Добавь фруктов","Оставь экономно"]);return proposal("По текущим условиям корзина выглядит нормально. Могу сделать её сытнее, дешевле или удобнее по готовке.",["Сытнее","Дешевле","Меньше готовки"])}if(/что лучше|что бы ты выбрал|посоветуй вариант/.test(t))return proposal("Я бы выбрал направление по твоей главной цели. Что сейчас важнее?",["Сытность","Экономия","Без готовки"]);return null}
  async function route(raw,history=[]){raw=String(raw||"").trim();if(!raw)return{ok:true,provider:"bai-brain-v2",operations:[],reply:""};memory.turns++;const pr=resolvePending(raw);if(pr)return{ok:true,provider:"bai-brain-v2",...pr};const t=low(raw),s=state(),ordered=products(raw),ids=uniq(ordered.map(x=>x.id)),shops=stores(raw),ops=[],advice=advisor(raw,s);if(advice)return advice;const b=budget(raw)||relativeBudget(raw,s.budget),p=people(raw),d=days(raw);if(/верни как было|отмени последнее|назад/.test(t))return{ok:true,provider:"bai-brain-v2",operations:[{type:"UNDO"}],reply:"Откатываю последнее изменение.",suggestions:[]};if(fresh(t))ops.push({type:"RESET_BASKET"});if(b)ops.push({type:"CHANGE_BUDGET",value:b});if(p)ops.push({type:"SET_PEOPLE",value:p});if(d)ops.push({type:"SET_DURATION",value:d});for(const st of shops)ops.push({type:"CHANGE_STORE",value:st});if(shops.length===1&&/только|в одном магазине/.test(t))ops.push({type:"SET_MODE",value:"one"});if(/нескольк.*магаз|по разным магазин|где дешевле/.test(t))ops.push({type:"SET_MODE",value:"multi"});ops.push(...prefs(t));if(only(t)&&ids.length){ops.push({type:"SET_INTENT",value:"only"},{type:"SET_ONLY_PRODUCTS",value:ids});memory.lastIntent="only"}else if(replace(t)&&ordered.length>=2){ops.push({type:"SET_INTENT",value:"replace"},{type:"REPLACE_PRODUCT",value:{from:ordered[0].id,to:ordered[ordered.length-1].id}});memory.lastIntent="replace"}else if(remove(t)&&ids.length){ops.push({type:"SET_INTENT",value:"remove"});ids.forEach(id=>ops.push({type:"REMOVE_PRODUCT",value:id}));memory.lastIntent="remove"}else if(add(t)&&ids.length){ops.push({type:"SET_INTENT",value:"add"});ids.forEach(id=>ops.push({type:"ADD_PRODUCT",value:id}));memory.lastIntent="add"}else if(ids.length){const cont=/^(а|и|еще|тогда|нет|ладно|ок)\b/.test(t)||Boolean(s.products?.length);if(!cont||fresh(t))ops.push({type:"CLEAR_ONLY"},{type:"SET_INTENT",value:"build"});ids.forEach(id=>ops.push({type:"REQUIRE",value:id}));memory.lastIntent=cont?"refine":"build"}
    const broad=/собери|подбери|корзин|что купить|чего взять|хочу еды|нужна еда|на вечер|на ужин/.test(t);if(broad&&!s.budget&&!b&&!/без бюджета|цена неважна/.test(t))return question("Какой бюджет держим? Можно примерно.",["До 1500 ₽","До 2500 ₽","Без жёсткого бюджета"],"budget");if(broad&&(!s.peopleCount||s.peopleCount===1)&&!p&&!/на одного|для себя|мне одному/.test(t)&&memory.turns<4)return question("На сколько человек собираем?",["На одного","На двоих","На троих"],"people");const hasStyle=/сыт|перекус|полез|эконом|бюджет|завтрак|ужин|готовить|быстро/.test(t)||Boolean((s.preferences||[]).length)||Boolean(s.cookingPreference);if(broad&&!hasStyle&&ids.length===0)return question("Какой вариант тебе ближе? Я от этого сильно по-разному соберу корзину.",["Сытно","Побольше перекусов","Полезнее","Максимально бюджетно"],"style");if(/не знаю что хочу|сам реши|на твой вкус|предложи сам|удиви/.test(t))return proposal("Могу пойти тремя путями. Выбирай настроение — дальше сам дособеру.",["Сытно и просто","Перекусы на вечер","Полезно и без возни"]);if(/готовить/.test(t)&&!/не хочу|лень|не буду|могу|люблю|нормально/.test(t))return question("Готовить готов или лучше почти без готовки?",["Почти без готовки","Готовить нормально"],"cooking");if(ops.length){if(!ops.some(o=>o.type==="REOPTIMIZE"))ops.push({type:"REOPTIMIZE"});let reply="Понял, обновляю корзину и сохраняю предыдущие условия.";if(ops.some(o=>o.type==="REMOVE_PRODUCT"))reply="Убрал. Остальные условия не трогаю.";else if(ops.some(o=>o.type==="ADD_PRODUCT"))reply="Добавил. Остальную корзину сохраняю.";else if(ops.some(o=>o.type==="REPLACE_PRODUCT"))reply="Понял, именно замена. Остальное оставляю как было.";else if(ops.some(o=>o.type==="SET_ONLY_PRODUCTS"))reply="Принял: только эти продукты, без лишнего.";else if(b||p||d)reply="Принял новые условия. Пересчитываю текущий вариант.";const next=[];if(!s.budget&&!b)next.push("Задать бюджет");if(!(s.preferences||[]).length&&!hasStyle)next.push("Сделать сытнее");if(!s.cookingPreference)next.push("Минимум готовки");return{ok:true,provider:"bai-brain-v2",operations:ops,reply,suggestions:next.slice(0,3),expectsAnswer:false}}
    return proposal("Я понял не всё и не хочу гадать. Скажи, что сейчас важнее: что добавить, что убрать или какой результат ты хочешь получить?",["Добавить продукты","Убрать лишнее","Собрать заново"])}
  function reset(){memory={pending:null,lastIntent:"build",turns:0,lastSuggestions:[]}}
  window.TDBaiBrain={route,reset,status:()=>({...memory})};
})();
