(() => {
  "use strict";
  const PRODUCTS={"молок":"milk","хлеб":"bread","куриц":"chicken","банан":"banana","масл":"oil","яйц":"eggs","яиц":"eggs","греч":"buck","сметан":"sour","сахар":"sugar","макарон":"pasta","вод":"water","яблок":"apple","ветчин":"ham","пельмен":"dumplings","лапш":"noodles","вафл":"waffles","творог":"cottage"};
  const STORES={"пятероч":"pyat","пятёроч":"pyat","магнит":"magnit","перекр":"perek","лент":"lenta","дикси":"dixy","лавк":"lavka","впрок":"vprok"};
  const NUM={"один":1,"одного":1,"одну":1,"одна":1,"два":2,"две":2,"двое":2,"двоих":2,"двух":2,"три":3,"трое":3,"троих":3,"трех":3,"четыре":4,"четверо":4,"четверых":4,"четырех":4,"пять":5,"шесть":6,"семь":7,"восемь":8,"девять":9,"десять":10,"полтора":1.5,"полторы":1.5};
  const uniq=a=>[...new Set((a||[]).filter(Boolean))],low=s=>String(s||"").toLowerCase().replace(/ё/g,"е"),state=()=>window.TDShoppingState?.get?.()||{};
  const emptyGoal=()=>({task:"basket",occasion:null,people:null,days:null,budget:null,cooking:null,preferences:[],requiredProducts:[],excludedProducts:[],onlyProducts:[],quantityTargets:{},stores:[],mode:null});
  let memory={pending:null,lastIntent:"build",lastProduct:null,turns:0,goal:emptyGoal()};
  function products(text){const t=low(text),out=[];for(const [stem,id] of Object.entries(PRODUCTS)){const p=t.indexOf(stem);if(p>=0)out.push({id,pos:p,stem})}return out.sort((a,b)=>a.pos-b.pos)}
  function replacementPair(text,ordered){if(!Array.isArray(ordered)||ordered.length<2)return null;const t=low(text),i=t.indexOf("вместо");if(i>=0){const before=ordered.filter(p=>p.pos<i),after=ordered.filter(p=>p.pos>i);if(before.length&&after.length)return{from:after[0].id,to:before[before.length-1].id};if(after.length>=2)return{from:after[0].id,to:after[after.length-1].id}}return{from:ordered[0].id,to:ordered[ordered.length-1].id}}
  function stores(text){const t=low(text),out=[];for(const [stem,id] of Object.entries(STORES))if(t.includes(stem))out.push(id);return uniq(out)}
  function number(v){if(!v)return null;if(/^\d+(?:[.,]\d+)?$/.test(v))return Number(v.replace(",","."));return NUM[low(v)]||null}
  function people(text){
    const t=low(text);let m=t.match(/(?:^|[^а-я])нас\s+(?:будет\s+)?(\d+|[а-я]+)(?=$|[\s,.!?])/);
    if(m){const n=number(m[1]);if(n)return n}
    m=t.match(/(?:^|[^а-я])(?:на|для|будет)\s+(\d+|[а-я]+)\s*(?:человек(?:а|у|ом|и)?|чел(?:\.|а)?|персон(?:ы|у)?|едок(?:а|ов)?)(?=$|[\s,.!?])/);
    if(m){const n=number(m[1]);if(n)return n}
    m=t.match(/(?:^|[^а-я])(?:на|для)\s+(одного|двоих|троих|четверых)(?=$|[\s,.!?])/);if(m)return number(m[1]);
    m=t.match(/(?:^|[^а-я])будет\s+(двое|трое|четверо)(?=$|[\s,.!?])/);if(m)return number(m[1]);
    if(/(?:^|[^а-я])мы\s+вдвоем(?=$|[\s,.!?])/.test(t))return 2;
    if(/(?:^|[^а-я])мы\s+втроем(?=$|[\s,.!?])/.test(t))return 3;
    if(/(?:^|[^а-я])мы\s+вчетвером(?=$|[\s,.!?])/.test(t))return 4;
    return null;
  }
  function days(text){
    const t=low(text);
    if(/(?:^|[^а-я])(?:на|примерно на)\s+(?:сегодня|завтра|день|сутки)(?=$|[\s,.!?])/.test(t))return 1;
    if(/(?:^|[^а-я])(?:на|примерно на)\s+пару\s+дн(?:я|ей)(?=$|[\s,.!?])/.test(t))return 2;
    if(/(?:^|[^а-я])(?:на|примерно на)\s+выходные(?=$|[\s,.!?])/.test(t))return 2;
    if(/(?:на|примерно на)\s+(?:одну\s+)?недел(?:ю|и)(?=$|[\s,.!?])/.test(t))return 7;
    const week=t.match(/(?:на|примерно на)\s+(\d+|[а-я]+)\s+недел(?:ю|и|ь)(?=$|[\s,.!?])/);if(week){const n=number(week[1]);if(n)return n*7}
    const m=t.match(/(?:на|примерно на)\s+(\d+|[а-я]+)\s*(?:день|дня|дней|сутки|суток)/);return m?number(m[1]):null;
  }
  function budget(text){const t=low(text);let m=t.match(/(?:до|бюджет(?:ом)?|улож(?:ись|иться) в|не больше|примерно|около)\s*([\d\s.,]+)\s*(?:р|руб|₽)/);if(m)return Number(m[1].replace(/\D/g,""));m=t.match(/(?:на)\s*([\d\s.,]+)\s*(?:р|руб|₽)/);return m?Number(m[1].replace(/\D/g,"")):null}
  function relativeBudget(text,current){const t=low(text);if(!current)return null;let m=t.match(/(?:дешевле|снизь|уменьши)\s*(?:на)?\s*(\d+)\s*%/);if(m)return Math.max(1,Math.round(current*(1-Number(m[1])/100)));m=t.match(/(?:дешевле|меньше|снизь|уменьши)\s+на\s+(\d+)\s*(?:р|руб|₽)?/);if(m)return Math.max(1,current-Number(m[1]));m=t.match(/(?:на\s+)?(\d+)\s*(?:р|руб|₽)?\s*(?:дешевле|меньше)/);if(m)return Math.max(1,current-Number(m[1]));if(/(?:дешевле|меньше|снизь|уменьши)\s+на\s+(?:косарь|тысячу|тыщу)/.test(t)||/(?:на\s+)?(?:косарь|тысячу|тыщу)\s*(?:дешевле|меньше)/.test(t))return Math.max(1,current-1000);if(/подешевле|дешевле|сэконом/.test(t))return Math.max(1,Math.round(current*.85));return null}
  const token=(t,body)=>new RegExp(`(^|[^а-яa-z0-9_])(?:${body})(?=$|[^а-яa-z0-9_])`,`i`).test(t);
  const fresh=t=>/с нуля|заново|новую корзин|начнем заново/.test(t),only=t=>token(t,"только|исключительно|лишь|одни|одних")||/корзин\w*\s+из\s+/.test(t),add=t=>token(t,"добав[а-я]*|докин[а-я]*|еще|плюс|положи"),remove=t=>token(t,"убери|удали|исключи|выкинь|без"),replace=t=>token(t,"замени|поменяй|вместо"),negatedAdd=t=>/(^|[\s,])не\s+(?:добав(?:ляй|лять|ь)?|докин(?:ь|уть)?|клади|положи)(?=\s|$|[,.!?])/.test(t);
  const normalizeUnit=u=>{u=low(u);if(/^кг|килограмм/.test(u))return"kg";if(/^г$|^гр|^грамм/.test(u))return"g";if(/^мл|миллилитр/.test(u))return"ml";if(/^л$|^литр/.test(u))return"l";if(/пач|упаков/.test(u))return"pack";if(/^шт|штук/.test(u))return"pcs";return null};
  function amounts(text,ordered){const t=low(text),out=[];const n="(\\d+(?:[.,]\\d+)?|один|одна|одну|два|две|три|четыре|пять|шесть|семь|восемь|девять|десять|полтора|полторы)",u="(кг|килограмм(?:а|ов)?|г|гр|грамм(?:а|ов)?|л|литр(?:а|ов)?|мл|миллилитр(?:а|ов)?|пачк(?:а|и|ек)?|упаковк(?:а|и|ок)?|шт|штук(?:а|и)?)";for(const p of ordered){const stem=p.stem.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");let m=t.match(new RegExp(n+"\\s*"+u+"\\s+[^,.!?]{0,18}"+stem))||t.match(new RegExp(stem+"[^,.!?]{0,18}?"+n+"\\s*"+u));if(m){const amount=number(String(m[1]))??Number(String(m[1]).replace(",",".")),unit=normalizeUnit(m[2]);if(amount>0&&unit)out.push({id:p.id,amount,unit});continue}if(["eggs","banana","apple"].includes(p.id)){m=t.match(new RegExp("(\\d+|один|одна|два|две|три|четыре|пять|шесть|семь|восемь|девять|десять)\\s+(?:шт\\.?\\s+)?[^,.!?]{0,10}"+stem));const amount=m?number(m[1]):null;if(amount>0)out.push({id:p.id,amount,unit:"pcs"})}}return out}
  function prefs(t){const ops=[];if(/готовить\s*(не хочу|лень|не буду)|без готовки|минимум готовки|быстро и просто/.test(t))ops.push({type:"SET_COOKING",value:"minimal"});if(/сытн|плотн|наесться/.test(t))ops.push({type:"ADD_PREFERENCE",value:"hearty"});if(/перекус|пожевать/.test(t))ops.push({type:"ADD_PREFERENCE",value:"snacks"});if(/полезн|здоров|пп\b/.test(t))ops.push({type:"ADD_PREFERENCE",value:"healthy"});if(/бюджетн|эконом/.test(t))ops.push({type:"ADD_PREFERENCE",value:"budget"});if(/фрукт/.test(t))ops.push({type:"PREFER",value:"фрукты"});if(/завтрак/.test(t))ops.push({type:"ADD_PREFERENCE",value:"breakfast"});if(/ужин|на вечер/.test(t))ops.push({type:"ADD_PREFERENCE",value:"dinner"});return ops}
  function mergeGoal(ops,text=""){const t=low(text);if(/ужин|на вечер/.test(t))memory.goal.occasion="dinner";else if(/завтрак/.test(t))memory.goal.occasion="breakfast";else if(/перекус/.test(t))memory.goal.occasion="snacks";for(const o of ops||[]){if(o.type==="RESET_BASKET")memory.goal=emptyGoal();else if(o.type==="CLEAR_ONLY"){memory.goal.onlyProducts=[]}else if(o.type==="CHANGE_BUDGET")memory.goal.budget=Number(o.value)||null;else if(o.type==="SET_PEOPLE")memory.goal.people=Number(o.value)||null;else if(o.type==="SET_DURATION")memory.goal.days=Number(o.value)||null;else if(o.type==="SET_COOKING")memory.goal.cooking=o.value;else if(o.type==="ADD_PREFERENCE"||o.type==="PREFER")memory.goal.preferences=uniq([...(memory.goal.preferences||[]),String(o.value)]);else if(o.type==="REQUIRE"||o.type==="ADD_PRODUCT"){memory.goal.requiredProducts=uniq([...(memory.goal.requiredProducts||[]),String(o.value)]);memory.lastProduct=String(o.value)}else if(o.type==="REMOVE_PRODUCT"){memory.goal.excludedProducts=uniq([...(memory.goal.excludedProducts||[]),String(o.value)]);memory.goal.requiredProducts=(memory.goal.requiredProducts||[]).filter(id=>id!==String(o.value));memory.lastProduct=String(o.value);delete memory.goal.quantityTargets[o.value]}else if(o.type==="SET_ONLY_PRODUCTS"){memory.goal.onlyProducts=uniq(o.value||[]);memory.goal.requiredProducts=uniq(o.value||[]);memory.lastProduct=memory.goal.onlyProducts.at(-1)||memory.lastProduct}else if(o.type==="SET_PRODUCT_AMOUNT"&&o.value?.id){memory.goal.quantityTargets[o.value.id]={amount:Number(o.value.amount),unit:o.value.unit};memory.lastProduct=o.value.id}else if(o.type==="CHANGE_STORE")memory.goal.stores=uniq([...(memory.goal.stores||[]),String(o.value)]);else if(o.type==="SET_MODE")memory.goal.mode=o.value;else if(o.type==="REPLACE_PRODUCT"&&o.value){memory.goal.excludedProducts=uniq([...(memory.goal.excludedProducts||[]),String(o.value.from)]);memory.goal.requiredProducts=uniq([...(memory.goal.requiredProducts||[]).filter(id=>id!==String(o.value.from)),String(o.value.to)]);memory.lastProduct=String(o.value.to);if(memory.goal.quantityTargets[o.value.from]&&!memory.goal.quantityTargets[o.value.to])memory.goal.quantityTargets[o.value.to]=memory.goal.quantityTargets[o.value.from];delete memory.goal.quantityTargets[o.value.from]}}}
  function dedupeOps(ops){const seen=new Set();return(ops||[]).filter(o=>{const k=o.type+":"+JSON.stringify(o.value??null);if(seen.has(k))return false;seen.add(k);return true})}
  function simpleProposal(reply,suggestions=[],expectsAnswer=true){return{ok:true,provider:"bai-brain-simple",operations:[],reply,suggestions:suggestions.slice(0,3),expectsAnswer,goal:JSON.parse(JSON.stringify(memory.goal))}}
  function mixedEdits(text,ops){let touched=false;for(const part of low(text).split(/\s+и\s+|,/)){const ps=uniq(products(part).map(x=>x.id));if(!ps.length)continue;if(remove(part)){ps.forEach(id=>ops.push({type:"REMOVE_PRODUCT",value:id}));touched=true}else if(add(part)){ps.forEach(id=>ops.push({type:"ADD_PRODUCT",value:id}));touched=true}}return touched}
  function scopedAddEdits(text,ordered,ops){const t=low(text),commands=[];const re=/(^|[\s,;])((?:не\s+)?(?:добав[а-я]*|докин[а-я]*|клади|положи))/g;let m;while((m=re.exec(t)))commands.push({pos:m.index+m[1].length,neg:/^не\s+/.test(m[2])});if(!commands.some(c=>c.neg))return false;let touched=false;for(const p of ordered){let command=null;for(const c of commands){if(c.pos<p.pos)command=c;else break}if(!command)continue;ops.push({type:command.neg?"REMOVE_PRODUCT":"ADD_PRODUCT",value:p.id});touched=true}return touched}
  async function route(raw){raw=String(raw||"").trim();if(!raw)return simpleProposal("");memory.turns++;const t=low(raw),s=state(),ordered=products(raw),ids=uniq(ordered.map(x=>x.id)),amountList=amounts(raw,ordered),shops=stores(raw),ops=[];const b=budget(raw)||relativeBudget(raw,s.budget||memory.goal.budget),p=people(raw),d=days(raw);
    if(/оставь как есть|ничего не меняй|не меняй ничего|пусть так и будет|все нормально как есть/.test(t))return simpleProposal("Оставляю как есть.",[],false);
    if(/верни как было|отмени последнее|назад/.test(t))return{ok:true,provider:"bai-brain-simple",operations:[{type:"UNDO"}],reply:"Откатываю.",suggestions:[],goal:JSON.parse(JSON.stringify(memory.goal))};
    if(/(?:возьми|поставь|добавь)?\s*что-нибудь\s+вместо\s+(?:этого|него|нее|неё)|замени\s+(?:это|его|ее|её)\s+на\s+что-нибудь/.test(t))return simpleProposal(memory.lastProduct?"На что заменить? Назови товар.":"Что именно заменить?",[]);
    if(/не надо столько|слишком много/.test(t)&&!ids.length)return simpleProposal(memory.lastProduct?"Сколько оставить?":"Какого товара стало слишком много?",[]);
    if(ids.length&&/(побольше|поменьше|больше|меньше)/.test(t)&&!amountList.length)return simpleProposal(`Сколько ${ids[0]==="milk"?"молока":ids[0]==="water"?"воды":"нужно"}?`,[]);
    if(remove(t)&&!ids.length&&token(t,"это|эту|этого|его|ее|её|хрень|штуку")){if(!memory.lastProduct)return simpleProposal("Что именно убрать?",[]);ops.push({type:"SET_INTENT",value:"remove"},{type:"REMOVE_PRODUCT",value:memory.lastProduct});memory.lastIntent="remove"}
    if(fresh(t)){ops.push({type:"RESET_BASKET"});memory.goal=emptyGoal();memory.lastProduct=null}
    if(b)ops.push({type:"CHANGE_BUDGET",value:b});if(p)ops.push({type:"SET_PEOPLE",value:p});if(d)ops.push({type:"SET_DURATION",value:d});for(const st of shops)ops.push({type:"CHANGE_STORE",value:st});
    if((shops.length===1&&/только|в одном магазине/.test(t))||/собери\s+в\s+одном\s+магазине|одним магазином/.test(t))ops.push({type:"SET_MODE",value:"one"});if(/нескольк.*магаз|по разным магазин|где дешевле/.test(t))ops.push({type:"SET_MODE",value:"multi"});if(/ужми до бюджета|уложи(?:сь)? в бюджет|не вылезай за бюджет/.test(t))ops.push({type:"ADD_PREFERENCE",value:"budget"});ops.push(...prefs(t));
    if(negatedAdd(t)&&ids.length&&scopedAddEdits(t,ordered,ops)){ops.push({type:"SET_INTENT",value:"edit"});memory.lastIntent="edit"}
    else if(remove(t)&&add(t)&&mixedEdits(t,ops)){memory.lastIntent="edit"}
    else if(only(t)&&ids.length){ops.push({type:"SET_INTENT",value:"only"},{type:"SET_ONLY_PRODUCTS",value:ids});memory.lastIntent="only"}
    else if(replace(t)&&ordered.length>=2){const pair=replacementPair(t,ordered);ops.push({type:"SET_INTENT",value:"replace"},{type:"REPLACE_PRODUCT",value:pair});memory.lastIntent="replace"}
    else if(replace(t)&&ordered.length===1&&/вместо\s+(этого|него|нее|неё)|замени\s+(это|его|ее|её)/.test(t)&&memory.lastProduct&&memory.lastProduct!==ordered[0].id){ops.push({type:"SET_INTENT",value:"replace"},{type:"REPLACE_PRODUCT",value:{from:memory.lastProduct,to:ordered[0].id}});memory.lastIntent="replace"}
    else if(remove(t)&&ids.length){ops.push({type:"SET_INTENT",value:"remove"});ids.forEach(id=>ops.push({type:"REMOVE_PRODUCT",value:id}));memory.lastIntent="remove"}
    else if(add(t)&&ids.length){ops.push({type:"SET_INTENT",value:"add"});ids.forEach(id=>ops.push({type:"ADD_PRODUCT",value:id}));memory.lastIntent="add"}
    else if(ids.length){const cont=/^(?:а|и|еще|тогда|ладно|ок|не)(?=$|[^а-яa-z0-9_])/.test(t)||Boolean(s.products?.length);if(!cont||fresh(t))ops.push({type:"CLEAR_ONLY"},{type:"SET_INTENT",value:"build"});ids.forEach(id=>ops.push({type:"REQUIRE",value:id}));memory.lastIntent=cont?"refine":"build"}
    else if(/собери|подбери|корзин|что купить|чего взять|хочу еды|нужна еда/.test(t)){ops.push({type:"CLEAR_ONLY"},{type:"SET_INTENT",value:"build"})}
    const removedIds=new Set(ops.filter(o=>o.type==="REMOVE_PRODUCT").map(o=>o.value));
    amountList.filter(x=>!removedIds.has(x.id)).forEach(x=>{if(!ops.some(o=>(o.type==="REQUIRE"||o.type==="ADD_PRODUCT")&&o.value===x.id))ops.push({type:"REQUIRE",value:x.id});ops.push({type:"SET_PRODUCT_AMOUNT",value:x})});
    if(/не знаю что хочу|сам реши|на твой вкус|предложи сам|простой вариант/.test(t)&&!ids.length){ops.push({type:"CLEAR_ONLY"},{type:"SET_INTENT",value:"build"},{type:"ADD_PREFERENCE",value:"balanced"})}
    if(/самый дешев|максимально дешев/.test(t)){ops.push({type:"SET_MODE",value:"multi"},{type:"ADD_PREFERENCE",value:"budget"})}
    if(!ops.length)return simpleProposal("Не понял, что изменить.",["Собрать заново"]);
    if(!ops.some(o=>o.type==="REOPTIMIZE"))ops.push({type:"REOPTIMIZE"});mergeGoal(ops,t);
    const hasRemove=ops.some(o=>o.type==="REMOVE_PRODUCT"),hasAdd=ops.some(o=>o.type==="ADD_PRODUCT");
    let reply="Готово.";if(hasRemove&&hasAdd)reply="Готово: убрал и добавил.";else if(hasRemove)reply="Убрал.";else if(ops.some(o=>o.type==="REPLACE_PRODUCT"))reply="Заменил.";else if(hasAdd)reply="Добавил.";else if(ops.some(o=>o.type==="SET_ONLY_PRODUCTS"))reply="Оставил только это.";else if(ops.some(o=>o.type==="SET_MODE"&&o.value==="one"))reply="Собираю в одном магазине.";else if(b&&!ids.length)reply=`Бюджет ${b} ₽.`;else if(p&&!ids.length)reply=`На ${p}.`;else if(d&&!ids.length)reply=`На ${d} дн.`;else if(/не знаю что хочу|сам реши|на твой вкус|предложи сам|простой вариант/.test(t))reply="Собрал простой вариант.";else if(/самый дешев|максимально дешев/.test(t))reply="Собрал максимально дёшево.";
    return{ok:true,provider:"bai-brain-simple",operations:dedupeOps(ops),reply,suggestions:[],expectsAnswer:false,goal:JSON.parse(JSON.stringify(memory.goal))}
  }
  function reset(){memory={pending:null,lastIntent:"build",lastProduct:null,turns:0,goal:emptyGoal()}}
  window.TDBaiBrain={route,reset,status:()=>JSON.parse(JSON.stringify(memory))};
})();
