(()=>{
  "use strict";
  const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const state=()=>window.TDShoppingState?.get?.()||{};const plan=()=>state().lastPlans?.[0]||null;const storeName=id=>(typeof STORES!=="undefined"?STORES:[]).find(x=>x.id===id)?.name||id||"Магазин";const money=v=>`${Math.round(Number(v)||0).toLocaleString("ru-RU")} ₽`;
  function point(){try{return JSON.parse(localStorage.getItem("td:selected-store-point")||"null")}catch{return null}}
  function groups(){const m=new Map();for(const p of plan()?.products||[]){const id=p.storeId||"store";if(!m.has(id))m.set(id,[]);m.get(id).push(p)}return [...m.entries()]}
  function pointFor(id){const p=point();return p&&(p.chainId===id||p.priceStoreId===id)?p:null}
  function text(time=""){const p=plan();if(!p?.products?.length)return"Корзина пока пустая.";const lines=["Самовывоз · Проще",time?`Когда забрать: ${time}`:"Когда забрать: не выбрано",""];for(const [id,items] of groups()){const pt=pointFor(id);lines.push(storeName(id));if(pt?.address)lines.push(`Точка: ${pt.address}`);for(const x of items)lines.push(`• ${x.name} — ${x.quantity||1} шт. · ${money((x.price||0)*(x.quantity||1))}`);lines.push("")}lines.push(`Итого: ≈ ${money(p.total)}`,"","Это список для похода. Заказ в магазин не отправлен.");return lines.join("\n")}
  async function copy(value){try{await navigator.clipboard.writeText(value);return true}catch{const t=document.createElement("textarea");t.value=value;document.body.appendChild(t);t.select();let ok=false;try{ok=document.execCommand("copy")}catch{}t.remove();return ok}}
  function close(){document.querySelector(".td-pickup-backdrop")?.remove()}
  function open(){const p=plan();if(!p?.products?.length)return;close();const back=document.createElement("div");back.className="td-pickup-backdrop";back.innerHTML=`<section class="td-pickup" role="dialog" aria-modal="true" aria-label="Самовывоз"><button class="td-pickup-x" type="button" aria-label="Закрыть">×</button><small>Самовывоз</small><h2>Готово к походу</h2><p class="td-pickup-lead">Выбери время и возьми список с собой. Мы ничего не отправляем в магазин.</p><label class="td-pickup-time">Когда забрать <input type="time" data-pickup-time></label><div class="td-pickup-stores">${groups().map(([id,items])=>{const pt=pointFor(id);return `<div><b>${esc(storeName(id))}</b>${pt?.address?`<address>${esc(pt.address)}</address>`:`<address>Точка не выбрана — можно выбрать её на карте магазинов</address>`}<span>${items.length} поз. · ≈ ${money(items.reduce((s,x)=>s+(Number(x.price)||0)*(Number(x.quantity)||1),0))}</span><ul>${items.map(x=>`<li>${esc(x.name)} <em>${x.quantity||1} шт.</em></li>`).join("")}</ul></div>`}).join("")}</div><div class="td-pickup-total"><span>Итого</span><b>≈ ${money(p.total)}</b></div><div class="td-pickup-actions"><button type="button" data-pickup-copy>Скопировать список</button><button type="button" data-pickup-share>Поделиться</button></div><p class="td-pickup-status" data-pickup-status>Заказ не создан. Это подготовленный список для самостоятельной покупки.</p></section>`;document.body.appendChild(back);back.querySelector(".td-pickup-x").onclick=close;back.onclick=e=>{if(e.target===back)close()};const time=()=>back.querySelector("[data-pickup-time]").value||"";back.querySelector("[data-pickup-copy]").onclick=async()=>{const ok=await copy(text(time()));back.querySelector("[data-pickup-status]").textContent=ok?"Список скопирован. Можно идти.":"Не получилось скопировать. Попробуй ещё раз."};back.querySelector("[data-pickup-share]").onclick=async()=>{const value=text(time());if(navigator.share){try{await navigator.share({title:"Самовывоз · Проще",text:value});return}catch(e){if(e?.name==="AbortError")return}}const ok=await copy(value);back.querySelector("[data-pickup-status]").textContent=ok?"Список скопирован — отправь его куда удобно.":"Не получилось подготовить список."}}
  function css(){if(document.querySelector("style[data-pickup-v1]"))return;const s=document.createElement("style");s.dataset.pickupV1="1";s.textContent=`.td-pickup-backdrop{position:fixed;inset:0;z-index:10050;background:rgba(8,18,13,.58);display:grid;place-items:end center;padding:16px}.td-pickup{position:relative;width:min(560px,100%);max-height:88vh;overflow:auto;background:#fff;border-radius:26px;padding:22px;box-shadow:0 24px 80px rgba(0,0,0,.24);font-family:inherit}.td-pickup-x{position:absolute;right:16px;top:14px;border:0;background:#eef4f0;width:36px;height:36px;border-radius:50%;font-size:24px}.td-pickup>small{color:#16834d;font-weight:800}.td-pickup h2{margin:5px 0 6px;font-size:26px}.td-pickup-lead,.td-pickup-status{color:#65736b;line-height:1.4}.td-pickup-time{display:grid;gap:7px;font-weight:750;margin:18px 0}.td-pickup-time input{font:inherit;padding:12px;border:1px solid #dce6e0;border-radius:14px}.td-pickup-stores{display:grid;gap:10px}.td-pickup-stores>div{border:1px solid #e3ebe6;border-radius:18px;padding:14px}.td-pickup-stores b{display:block}.td-pickup-stores address{font-size:12px;color:#68766e;font-style:normal;margin:3px 0}.td-pickup-stores span{font-size:13px;color:#68766e}.td-pickup-stores ul{padding:0;margin:10px 0 0;list-style:none;display:grid;gap:6px}.td-pickup-stores li{display:flex;justify-content:space-between;gap:12px}.td-pickup-stores em{font-style:normal;color:#68766e;white-space:nowrap}.td-pickup-total{display:flex;justify-content:space-between;align-items:center;padding:16px 2px;font-size:18px}.td-pickup-actions{display:grid;grid-template-columns:1fr 1fr;gap:9px}.td-pickup-actions button{border:0;border-radius:15px;padding:13px;font:inherit;font-weight:800;background:#102018;color:#fff}.td-pickup-actions button+button{background:#e9f8ef;color:#126a40}@media(max-width:520px){.td-pickup-backdrop{padding:0;align-items:end}.td-pickup{border-radius:24px 24px 0 0;padding:20px 16px}.td-pickup-actions{grid-template-columns:1fr}}`;document.head.appendChild(s)}
  css();window.TDPickupFlowV1={open,close,text};
})();