(()=>{
  "use strict";
  const KEY="td:purchase-proof-v1",MAX=100;
  const read=()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(x)?x:[]}catch{return[]}};
  const write=x=>localStorage.setItem(KEY,JSON.stringify(x.slice(-MAX)));
  const money=v=>`${Math.round(Number(v)||0).toLocaleString("ru-RU")} ₽`;
  const state=()=>window.TDShoppingState?.get?.()||{};
  const plan=()=>state().lastPlans?.[0]||null;
  const receiptModule=()=>window.TDReceiptProofV2?Promise.resolve(window.TDReceiptProofV2):import("./receipt-proof-v2.js?v=20260911-receipt-proof-v2").then(()=>window.TDReceiptProofV2);
  function entries(){return read().sort((a,b)=>String(b.at).localeCompare(String(a.at)))}
  function stats(){const rows=entries(),verified=rows.filter(x=>x.proof==="receipt_verified"),pending=rows.filter(x=>x.proof==="receipt_pending"),self=rows.filter(x=>x.proof==="self");return{purchases:rows.length,selfPurchases:self.length,receiptPurchases:verified.length,receiptPending:pending.length,actualTotal:verified.reduce((s,x)=>s+Number(x.actualSaving||0),0),reportedTotal:rows.reduce((s,x)=>s+Number(x.actualSaving||0),0),latest:rows[0]||null}}
  function snapshot(){const p=plan();if(!p?.products?.length)return null;const baseline=(state().lastPlans||[]).find(x=>x.type==="one")||null;return{planId:p.id||"",planType:p.type||"",plannedTotal:Math.round(Number(p.total)||0),baselineTotal:Math.round(Number(baseline?.total)||0),cart:Object.fromEntries((p.products||[]).map(x=>[x.id,x.quantity||1]))}}
  function save(input={}){const snap=snapshot();if(!snap)return null;const actualTotal=Math.round(Number(input.actualTotal)||snap.plannedTotal),actualSaving=snap.baselineTotal>0?Math.max(0,snap.baselineTotal-actualTotal):0,proof=["self","receipt_pending","receipt_verified"].includes(input.proof)?input.proof:"self";const row={id:crypto.randomUUID?.()||String(Date.now()),at:new Date().toISOString(),proof,receiptRef:input.receiptRef||null,actualTotal,actualSaving,note:String(input.note||"").slice(0,160),...snap};const rows=read();rows.push(row);write(rows);window.dispatchEvent(new CustomEvent("td:purchase-confirmed",{detail:row}));return row}
  function close(){document.querySelector(".td-purchase-proof")?.remove()}
  async function openReceipt(snap,status){try{const mod=await receiptModule();if(!mod?.open)throw new Error("receipt module unavailable");close();mod.open({plannedTotal:snap.plannedTotal,onSaved:receipt=>{const row=save({actualTotal:receipt.total,proof:"receipt_pending",receiptRef:receipt.id});window.dispatchEvent(new CustomEvent("td:purchase-receipt-linked",{detail:{purchase:row,receipt}}))}})}catch(e){console.warn("[Purchase Proof] receipt open failed",e);if(status)status.textContent="Чек не открылся. Попробуй ещё раз."}}
  function open(){const snap=snapshot();if(!snap)return;close();const root=document.createElement("section");root.className="td-purchase-proof";root.innerHTML=`<div class="td-purchase-proof-card"><button type="button" data-proof-close>×</button><small>После магазина</small><h3>Покупка состоялась?</h3><p>Плановая корзина: <b>${money(snap.plannedTotal)}</b></p><label>Фактически заплатил<input data-proof-total inputmode="numeric" value="${snap.plannedTotal}"></label><div class="td-proof-actions"><button type="button" data-proof-self>Подтвердить без чека</button><button type="button" data-proof-receipt>Добавить фото чека</button></div><p class="td-proof-note">Без чека сумма считается сообщённой пользователем. Чек сначала сохраняется как черновик и не становится «проверенным» автоматически.</p><div data-proof-status></div></div>`;document.body.appendChild(root);const status=root.querySelector("[data-proof-status]");root.querySelector("[data-proof-close]").onclick=close;root.onclick=e=>{if(e.target===root)close()};root.querySelector("[data-proof-self]").onclick=()=>{const total=Number(String(root.querySelector("[data-proof-total]").value).replace(/[^0-9]/g,""));if(!total){status.textContent="Укажи итоговую сумму.";return}const row=save({actualTotal:total,proof:"self"});if(row){status.textContent=`Покупка сохранена${row.actualSaving>0?` · экономия по твоей сумме ${money(row.actualSaving)}`:""}.`;setTimeout(close,1000)}};root.querySelector("[data-proof-receipt]").onclick=()=>openReceipt(snap,status)}
  function css(){if(document.querySelector("style[data-purchase-proof-css]"))return;const s=document.createElement("style");s.dataset.purchaseProofCss="1";s.textContent=`.td-purchase-proof{position:fixed;inset:0;z-index:420;background:rgba(20,18,14,.52);display:grid;align-items:end;padding:12px}.td-purchase-proof-card{position:relative;background:#fff;border-radius:24px;padding:20px;max-width:430px;width:100%;margin:0 auto;font-family:Manrope,sans-serif}.td-purchase-proof-card>[data-proof-close]{position:absolute;right:14px;top:12px;border:0;background:#f2efe9;border-radius:50%;width:34px;height:34px;font-size:20px}.td-purchase-proof-card small{font-weight:800;color:#6b6458}.td-purchase-proof-card h3{font-size:22px;margin:4px 0 8px}.td-purchase-proof-card p{font-size:12px}.td-purchase-proof-card label{display:block;font-size:11px;font-weight:800;margin-top:12px}.td-purchase-proof-card input{box-sizing:border-box;width:100%;margin-top:5px;border:1px solid #ddd5c9;border-radius:13px;padding:12px;background:#faf8f4;font:800 14px Manrope,sans-serif}.td-proof-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:14px}.td-proof-actions button{border:0;border-radius:14px;padding:12px;font:900 12px Manrope,sans-serif}.td-proof-actions [data-proof-self]{background:#161410;color:#fff}.td-proof-actions [data-proof-receipt]{background:#e8f3ea;color:#0f7b4a}.td-proof-note{color:#6b6458;line-height:1.45;margin-top:10px}[data-proof-status]{font-size:11px;font-weight:800;margin-top:9px}`;document.head.appendChild(s)}
  css();window.TDPurchaseProof={open,close,save,entries,stats};
})();