(()=>{
  "use strict";
  const KEY="td:purchase-proof-v1",MAX=100;
  const read=()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(x)?x:[]}catch{return[]}};
  const write=x=>localStorage.setItem(KEY,JSON.stringify(x.slice(-MAX)));
  const money=v=>`${Math.round(Number(v)||0).toLocaleString("ru-RU")} ₽`;
  const state=()=>window.TDShoppingState?.get?.()||{};
  const plan=()=>state().lastPlans?.[0]||null;
  function entries(){return read().sort((a,b)=>String(b.at).localeCompare(String(a.at)))}
  function stats(){const rows=entries(),receipt=rows.filter(x=>x.proof==="receipt");return{purchases:rows.length,receiptPurchases:receipt.length,actualTotal:receipt.reduce((s,x)=>s+Number(x.actualSaving||0),0),latest:rows[0]||null}}
  function snapshot(){const p=plan();if(!p?.products?.length)return null;const baseline=(state().lastPlans||[]).find(x=>x.type==="one")||null;return{planId:p.id||"",planType:p.type||"",plannedTotal:Math.round(Number(p.total)||0),baselineTotal:Math.round(Number(baseline?.total)||0),cart:Object.fromEntries((p.products||[]).map(x=>[x.id,x.quantity||1]))}}
  function save(input={}){const snap=snapshot();if(!snap)return null;const actualTotal=Math.round(Number(input.actualTotal)||snap.plannedTotal),actualSaving=snap.baselineTotal>0?Math.max(0,snap.baselineTotal-actualTotal):0;const row={id:crypto.randomUUID?.()||String(Date.now()),at:new Date().toISOString(),proof:input.proof==="receipt"?"receipt":"self",actualTotal,actualSaving,note:String(input.note||"").slice(0,160),...snap};const rows=read();rows.push(row);write(rows);window.dispatchEvent(new CustomEvent("td:purchase-confirmed",{detail:row}));return row}
  function close(){document.querySelector(".td-purchase-proof")?.remove()}
  function open(){const snap=snapshot();if(!snap)return;close();const root=document.createElement("section");root.className="td-purchase-proof";root.innerHTML=`<div class="td-purchase-proof-card"><button type="button" data-proof-close>×</button><small>После магазина</small><h3>Покупка состоялась?</h3><p>Плановая корзина: <b>${money(snap.plannedTotal)}</b></p><label>Фактически заплатил<input data-proof-total inputmode="numeric" value="${snap.plannedTotal}"></label><label>Подтверждение<select data-proof-kind><option value="self">Подтверждаю сам</option><option value="receipt">Есть чек</option></select></label><p class="td-proof-note">«Есть чек» пока означает ручное подтверждение суммы. Фото чека и распознавание добавим отдельно — приложение не будет делать вид, что чек проверен автоматически.</p><button type="button" data-proof-save>Сохранить покупку</button><div data-proof-status></div></div>`;document.body.appendChild(root);root.querySelector("[data-proof-close]").onclick=close;root.onclick=e=>{if(e.target===root)close()};root.querySelector("[data-proof-save]").onclick=()=>{const total=Number(String(root.querySelector("[data-proof-total]").value).replace(/[^0-9]/g,""));if(!total){root.querySelector("[data-proof-status]").textContent="Укажи итоговую сумму.";return}const row=save({actualTotal:total,proof:root.querySelector("[data-proof-kind]").value});if(row){root.querySelector("[data-proof-status]").textContent=`Покупка сохранена${row.actualSaving>0?` · фактическая экономия ${money(row.actualSaving)}`:""}.`;setTimeout(close,1200)}}}
  function css(){if(document.querySelector("style[data-purchase-proof-css]"))return;const s=document.createElement("style");s.dataset.purchaseProofCss="1";s.textContent=`.td-purchase-proof{position:fixed;inset:0;z-index:420;background:rgba(20,18,14,.52);display:grid;align-items:end;padding:12px}.td-purchase-proof-card{position:relative;background:#fff;border-radius:24px;padding:20px;max-width:430px;width:100%;margin:0 auto;font-family:Manrope,sans-serif}.td-purchase-proof-card>[data-proof-close]{position:absolute;right:14px;top:12px;border:0;background:#f2efe9;border-radius:50%;width:34px;height:34px;font-size:20px}.td-purchase-proof-card small{font-weight:800;color:#777}.td-purchase-proof-card h3{font-size:22px;margin:4px 0 8px}.td-purchase-proof-card p{font-size:12px}.td-purchase-proof-card label{display:block;font-size:11px;font-weight:800;margin-top:12px}.td-purchase-proof-card input,.td-purchase-proof-card select{box-sizing:border-box;width:100%;margin-top:5px;border:1px solid #ddd5c9;border-radius:13px;padding:12px;background:#faf8f4;font:800 14px Manrope,sans-serif}.td-purchase-proof-card>[data-proof-save]{width:100%;border:0;border-radius:14px;padding:13px;margin-top:14px;background:#161410;color:#fff;font:900 13px Manrope,sans-serif}.td-proof-note{color:#756e63;line-height:1.45;margin-top:10px}[data-proof-status]{font-size:11px;font-weight:800;margin-top:9px}`;document.head.appendChild(s)}
  css();window.TDPurchaseProof={open,close,save,entries,stats};
})();