(() => {
  "use strict";
  const STORAGE={provider:"td_bai_provider",endpoint:"td_bai_cloud_endpoint",model:"td_bai_cloud_model",apiKey:"td_bai_cloud_key"};
  const BROWSER_MODEL="onnx-community/Qwen3-0.6B-ONNX";
  const CLOUD_MODEL="qwen3.7-plus";
  const ALLOWED=new Set(["UNDO","RESET_BASKET","SET_INTENT","SET_ONLY_PRODUCTS","CLEAR_ONLY","ADD_PRODUCT","REPLACE_PRODUCT","CHANGE_BUDGET","SET_PEOPLE","SET_DURATION","SET_COOKING","ADD_PREFERENCE","CHANGE_STORE","SET_MODE","REMOVE_PRODUCT","REQUIRE","PREFER","EXCLUDE_BRAND","HAS_AT_HOME","EXCLUDE_TAG","REOPTIMIZE","ASK_CLARIFICATION","NOTE"]);
  let worker=null,seq=0; const pending=new Map();
  const get=k=>{try{return localStorage.getItem(k)}catch{return null}};
  const set=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};
  const cloudReady=()=>Boolean(get(STORAGE.endpoint)&&get(STORAGE.apiKey));
  const provider=()=>cloudReady()?"cloud":(navigator.gpu?"browser":"rules");
  function stateContext(){const s=window.TDShoppingState?.get?.()||{};return{budget:s.budget||null,people:s.peopleCount||1,days:s.duration||1,cooking:s.cookingPreference||null,mode:s.mode||null,stores:s.stores||[],intent:s.intent||"build",only:s.onlyProducts||[],required:s.requiredProducts||[],preferred:s.preferredProducts||[],excluded:s.excludedProducts||[],existing:s.existingProducts||[],products:(s.products||[]).map(x=>({id:x.id,name:x.name,qty:x.quantity,price:x.price})),total:s.currentTotal||0};}
  function prompt(){return `Ты Бай — умный разговорный агент сервиса «Там дешевле». Понимай живую русскую речь и контекст диалога. Ты НЕ считаешь и НЕ выдумываешь цены: цены и корзину исполняет код. Верни только JSON {"reply":"короткий естественный ответ Бая","operations":[...]}. Если данных не хватает для осмысленного действия — задай один конкретный вопрос через ASK_CLARIFICATION и reply. Сохраняй предыдущие ограничения, если пользователь явно их не отменил. Короткие реплики — продолжение текущего диалога.\nОперации: RESET_BASKET,SET_INTENT,SET_ONLY_PRODUCTS,CLEAR_ONLY,ADD_PRODUCT,REPLACE_PRODUCT,CHANGE_BUDGET,SET_PEOPLE,SET_DURATION,SET_COOKING,ADD_PREFERENCE,CHANGE_STORE,SET_MODE,REMOVE_PRODUCT,REQUIRE,PREFER,EXCLUDE_BRAND,HAS_AT_HOME,EXCLUDE_TAG,REOPTIMIZE,ASK_CLARIFICATION,NOTE,UNDO.\nПродукты: milk,bread,chicken,banana,oil,eggs,buck,sour,sugar,pasta,water,apple,ham,dumplings,noodles,waffles,cottage. Магазины: pyat,magnit,perek,lenta,dixy,lavka,vprok.\nПримеры: «а теперь на четверых» => SET_PEOPLE 4 + REOPTIMIZE. «нет, молоко убери» => REMOVE_PRODUCT milk. «хочу сытно, но готовить вообще не хочу» => SET_COOKING minimal + ADD_PREFERENCE hearty + REOPTIMIZE. «что-нибудь нормальное» при недостатке контекста => ASK_CLARIFICATION.`;}
  function msgs(text,history=[]){const recent=(history||[]).slice(-8).map(m=>({role:m.role==="assistant"?"assistant":"user",content:String(m.text||"").slice(0,500)}));return[{role:"system",content:prompt()},...recent,{role:"user",content:`Состояние покупок: ${JSON.stringify(stateContext())}\nСообщение: ${text}`}];}
  function parse(text){const raw=String(text||"").trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/,""),a=raw.indexOf("{"),b=raw.lastIndexOf("}");if(a<0||b<a)throw Error("no json");const x=JSON.parse(raw.slice(a,b+1));const operations=Array.isArray(x.operations)?x.operations.filter(o=>o&&ALLOWED.has(o.type)).slice(0,24).map(o=>({type:o.type,value:o.value})):[];return{operations,reply:typeof x.reply==="string"?x.reply.trim():""};}
  async function cloud(text,history){const endpoint=get(STORAGE.endpoint).replace(/\/$/,"")+"/chat/completions";const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+get(STORAGE.apiKey)},body:JSON.stringify({model:get(STORAGE.model)||CLOUD_MODEL,messages:msgs(text,history),temperature:.25,response_format:{type:"json_object"}})});if(!r.ok)throw Error("cloud "+r.status);const d=await r.json();return{ok:true,provider:"cloud",model:get(STORAGE.model)||CLOUD_MODEL,...parse(d?.choices?.[0]?.message?.content)};}
  function ensureWorker(){if(worker)return worker;if(!navigator.gpu)throw Error("WebGPU unavailable");worker=new Worker(new URL("qwen-browser-worker.js",location.href),{type:"module"});worker.onmessage=e=>{const d=e.data||{},p=pending.get(d.id);if(!p)return;if(d.type==="result"){pending.delete(d.id);p.resolve(d.text)}else if(d.type==="error"){pending.delete(d.id);p.reject(Error(d.error||"worker"))}};return worker;}
  async function browser(text,history){const w=ensureWorker(),id=++seq,out=await new Promise((resolve,reject)=>{const t=setTimeout(()=>{pending.delete(id);reject(Error("timeout"))},90000);pending.set(id,{resolve:v=>{clearTimeout(t);resolve(v)},reject:e=>{clearTimeout(t);reject(e)}});w.postMessage({type:"generate",id,messages:msgs(text,history)})});return{ok:true,provider:"browser",model:BROWSER_MODEL,...parse(out)};}
  async function route(text,history=[]){try{if(cloudReady())return await cloud(text,history);if(navigator.gpu)return await browser(text,history)}catch(e){console.warn("[Bai Brain]",e)}return{ok:true,provider:"rules",operations:null,reply:""};}
  window.TDQwenRouter={route,status:()=>({provider:provider(),cloudReady:cloudReady(),model:cloudReady()?(get(STORAGE.model)||CLOUD_MODEL):BROWSER_MODEL}),configureCloud({endpoint,apiKey,model}={}){if(endpoint)set(STORAGE.endpoint,endpoint);if(apiKey)set(STORAGE.apiKey,apiKey);if(model)set(STORAGE.model,model);set(STORAGE.provider,"cloud");return this.status()},clearCloud(){localStorage.removeItem(STORAGE.endpoint);localStorage.removeItem(STORAGE.apiKey);localStorage.removeItem(STORAGE.model);return this.status()}};
})();
