(() => {
  "use strict";
  const STORAGE={enabled:"td_qwen_enabled",provider:"td_qwen_provider",endpoint:"td_qwen_endpoint",model:"td_qwen_model"};
  const DEFAULT_ENDPOINT="http://127.0.0.1:11434/v1/chat/completions";
  const DEFAULT_MODEL="qwen3:4b";
  const BROWSER_MODEL="onnx-community/Qwen3-0.6B-ONNX";
  const ALLOWED=new Set(["UNDO","RESET_BASKET","SET_INTENT","SET_ONLY_PRODUCTS","CLEAR_ONLY","ADD_PRODUCT","REPLACE_PRODUCT","CHANGE_BUDGET","SET_PEOPLE","SET_DURATION","SET_COOKING","ADD_PREFERENCE","CHANGE_STORE","SET_MODE","REMOVE_PRODUCT","REQUIRE","PREFER","EXCLUDE_BRAND","HAS_AT_HOME","EXCLUDE_TAG","NOTE"]);
  const STRONG_INTENTS=new Set(["SET_ONLY_PRODUCTS","REPLACE_PRODUCT","RESET_BASKET","ADD_PRODUCT","REMOVE_PRODUCT"]);
  let browserWorker=null,browserSeq=0;const browserPending=new Map();
  const get=key=>{try{return localStorage.getItem(key)}catch{return null}};const set=(key,value)=>{try{localStorage.setItem(key,value)}catch{}};const remove=key=>{try{localStorage.removeItem(key)}catch{}};
  const enabled=()=>get(STORAGE.enabled)==="1";const provider=()=>enabled()?(get(STORAGE.provider)||"ollama"):"rules";const config=()=>({enabled:enabled(),provider:provider(),endpoint:get(STORAGE.endpoint)||DEFAULT_ENDPOINT,model:get(STORAGE.model)||DEFAULT_MODEL,browserModel:BROWSER_MODEL,webgpu:Boolean(navigator.gpu)});
  function emit(state,extra={}){window.dispatchEvent(new CustomEvent("td:qwen-status",{detail:{state,...config(),...extra}}));}
  function normalizeProgress(value){let n=Number(value);if(!Number.isFinite(n))return null;if(n>=0&&n<=1)n*=100;return Math.max(0,Math.min(100,Math.round(n)));}
  function cleanJson(text){const raw=String(text||"").trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/,"");const first=raw.indexOf("{"),last=raw.lastIndexOf("}");if(first<0||last<first)throw new Error("Qwen returned no JSON");return JSON.parse(raw.slice(first,last+1));}
  function validateOperations(value){if(!Array.isArray(value))return null;const ops=value.filter(op=>op&&ALLOWED.has(op.type)).slice(0,24).map(op=>({type:op.type,value:op.value}));return ops.length?ops:null;}
  function stateContext(){const s=window.TDShoppingState?.get?.();if(!s)return{};return{budget:s.budget||null,peopleCount:s.peopleCount||null,duration:s.duration||null,mode:s.mode||null,stores:s.stores||[],intent:s.intent||"build",selectionMode:s.selectionMode||"auto",onlyProducts:s.onlyProducts||[],requiredProducts:s.requiredProducts||[],preferredProducts:s.preferredProducts||[],excludedBrands:s.excludedBrands||[],existingProducts:s.existingProducts||[]};}
  function systemPrompt(){return `Ты маршрутизатор намерений ассистента покупок «Бай». Верни только JSON: {"operations":[...]}. Не рассуждай и не придумывай цены.\nРазличай смысл:\n- «только/одни/исключительно X» => SET_INTENT=only + SET_ONLY_PRODUCTS=[id]. Никаких других товаров.\n- «добавь X» => SET_INTENT=add + ADD_PRODUCT. Не заменяй всю корзину.\n- «убери X» => SET_INTENT=remove + REMOVE_PRODUCT.\n- «замени X на Y» => SET_INTENT=replace + REPLACE_PRODUCT={"from":"x","to":"y"}.\n- «собери с нуля/заново» => RESET_BASKET, затем остальные ограничения.\n- обычное «собери еду...» => SET_INTENT=build, можно REQUIRE/PREFER.\nРазрешённые type: RESET_BASKET, SET_INTENT, SET_ONLY_PRODUCTS, CLEAR_ONLY, ADD_PRODUCT, REPLACE_PRODUCT, CHANGE_BUDGET, SET_PEOPLE, SET_DURATION, SET_COOKING, ADD_PREFERENCE, CHANGE_STORE, SET_MODE, REMOVE_PRODUCT, REQUIRE, PREFER, EXCLUDE_BRAND, HAS_AT_HOME, EXCLUDE_TAG, NOTE, UNDO.\nМагазины: pyat, magnit, perek, lenta, dixy, lavka, vprok.\nПродукты: milk, bread, chicken, banana, oil, eggs, buck, sour, sugar, pasta, water, apple, ham, dumplings, noodles, waffles, cottage.\nПример: «корзина на 1700, чтобы там были просто бананы» => {"operations":[{"type":"CHANGE_BUDGET","value":1700},{"type":"SET_INTENT","value":"only"},{"type":"SET_ONLY_PRODUCTS","value":["banana"]}]}.\nПример: «добавь яблоки» => {"operations":[{"type":"SET_INTENT","value":"add"},{"type":"ADD_PRODUCT","value":"apple"}]}.`}
  function messages(text){return[{role:"system",content:systemPrompt()},{role:"user",content:`Текущее состояние: ${JSON.stringify(stateContext())}\nКоманда: ${text}\n/no_think`}];}
  function semanticRules(text){try{const ops=window.TDShoppingConversation?.parse?.(text);if(!Array.isArray(ops)||!ops.length)return null;return ops.some(op=>STRONG_INTENTS.has(op.type))?ops:null}catch{return null}}
  async function callOllama(text){const cfg=config(),controller=new AbortController();const timer=setTimeout(()=>controller.abort(),5000);emit("thinking",{provider:"ollama"});try{const response=await fetch(cfg.endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:cfg.model,messages:messages(text),temperature:0.05,stream:false}),signal:controller.signal});if(!response.ok)throw new Error(`Qwen HTTP ${response.status}`);const data=await response.json();const parsed=cleanJson(data?.choices?.[0]?.message?.content);const operations=validateOperations(parsed.operations);if(!operations)throw new Error("Qwen returned invalid operations");emit("ready",{provider:"ollama"});return{ok:true,provider:"ollama",model:cfg.model,operations};}finally{clearTimeout(timer)}}
  function ensureBrowserWorker(){if(!navigator.gpu)throw new Error("WebGPU unavailable");if(browserWorker)return browserWorker;browserWorker=new Worker(new URL("qwen-browser-worker.js",location.href),{type:"module"});browserWorker.onmessage=event=>{const data=event.data||{};if(data.type==="progress"){emit("loading",{provider:"browser",progress:normalizeProgress(data.data?.progress),file:data.data?.file||null});return}const pending=browserPending.get(data.id);if(!pending)return;browserPending.delete(data.id);if(data.type==="result")pending.resolve(data.text);else pending.reject(new Error(data.error||"Browser Qwen failed"));};browserWorker.onerror=error=>{for(const pending of browserPending.values())pending.reject(new Error(error.message||"Browser worker failed"));browserPending.clear();browserWorker?.terminate();browserWorker=null;};return browserWorker;}
  async function callBrowser(text){emit("loading",{provider:"browser",progress:0});const worker=ensureBrowserWorker(),id=++browserSeq;const output=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{browserPending.delete(id);reject(new Error("Browser Qwen timeout"));},90000);browserPending.set(id,{resolve:value=>{clearTimeout(timer);resolve(value)},reject:error=>{clearTimeout(timer);reject(error)}});worker.postMessage({type:"generate",id,messages:messages(text)});});const parsed=cleanJson(output),operations=validateOperations(parsed.operations);if(!operations)throw new Error("Browser Qwen returned invalid operations");emit("ready",{provider:"browser",progress:100});return{ok:true,provider:"browser",model:BROWSER_MODEL,operations};}
  async function probe(){const cfg=config();if(cfg.provider==="browser")return{ok:Boolean(navigator.gpu),provider:"browser",reason:navigator.gpu?null:"WebGPU unavailable"};if(cfg.provider!=="ollama")return{ok:true,provider:"rules"};const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),1800);try{const base=cfg.endpoint.replace(/\/v1\/chat\/completions\/?$/,"");const response=await fetch(base,{signal:controller.signal});return{ok:response.ok,provider:"ollama",status:response.status};}catch(error){return{ok:false,provider:"ollama",reason:String(error?.message||error)}}finally{clearTimeout(timer)}}
  async function route(text){const deterministic=semanticRules(text);if(deterministic)return{ok:true,provider:"semantic-rules",operations:deterministic};const mode=provider();if(mode==="rules")return{ok:true,provider:"rules",operations:null};try{if(mode==="browser")return await callBrowser(text);return await callOllama(text)}catch(error){console.warn("[TD Qwen] fallback to local rules:",error);emit("fallback",{provider:mode,error:String(error?.message||error)});return{ok:true,provider:"rules",operations:null,error:String(error?.message||error)}}}
  window.TDQwenRouter={route,probe,status:config,enableBrowser(){if(!navigator.gpu)return{ok:false,...config(),reason:"WebGPU unavailable"};set(STORAGE.enabled,"1");set(STORAGE.provider,"browser");emit("enabled",{provider:"browser"});return{ok:true,...config()}},enableOllama(options={}){if(options.endpoint)set(STORAGE.endpoint,options.endpoint);if(options.model)set(STORAGE.model,options.model);set(STORAGE.enabled,"1");set(STORAGE.provider,"ollama");emit("enabled",{provider:"ollama"});return{ok:true,...config()}},enable(options={}){return this.enableOllama(options)},disable(){remove(STORAGE.enabled);remove(STORAGE.provider);emit("disabled",{provider:"rules"});return config()},configure(options={}){if(options.endpoint)set(STORAGE.endpoint,options.endpoint);if(options.model)set(STORAGE.model,options.model);if(options.provider)set(STORAGE.provider,options.provider);return config()},reset(){Object.values(STORAGE).forEach(remove);browserWorker?.terminate();browserWorker=null;emit("reset",{provider:"rules"});return config()}};
})();
