(()=>{
  "use strict";
  const KEY="td:saved-baskets:v1",MAX=5,FIELDS=["budget","location","stores","existingProducts","requiredProducts","preferredProducts","excludedProducts","excludedBrands","onlyProducts","quantityTargets","selectionMode","intent","preferences","cookingPreference","deliveryPreference","peopleCount","duration","userNotes","mode"];
  const read=()=>{try{const v=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(v)?v:[]}catch{return[]}};
  const write=rows=>{localStorage.setItem(KEY,JSON.stringify(rows.slice(0,MAX)));window.dispatchEvent(new CustomEvent("td:saved-baskets",{detail:{count:rows.length}}));return rows};
  const clone=v=>JSON.parse(JSON.stringify(v));
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const money=v=>Math.round(Number(v)||0).toLocaleString("ru-RU")+" ₽";
  function currentSnapshot(){const s=window.TDShoppingState?.get?.();if(!s)return null;const snap={};for(const k of FIELDS)snap[k]=clone(s[k]);return snap}
  function suggestedName(){const plan=window.TDShoppingState?.get?.().lastPlans?.[0],names=(plan?.products||[]).slice(0,2).map(x=>x.name).filter(Boolean);return names.length?names.join(" + "):"Моя корзина"}
  function ensureInitialHistory(row){const h=window.TDBasketPriceHistory;if(!h||!row?.snapshot||!row.total)return;const st=h.stats(row.id);if(st.count)return;h.record({basketId:row.id,name:row.name,signature:h.signature(row.snapshot,[]),total:row.total,at:row.createdAt,source:"saved"})}
  function historyHtml(row){ensureInitialHistory(row);const st=window.TDBasketPriceHistory?.stats?.(row.id);if(!st?.count)return"";const latest=st.latest?.total??row.total;if(st.count<2)return `<div class="td-saved-basket-history">История цены началась с ${money(latest)}.</div>`;const sign=st.delta<0?"−":st.delta>0?"+":"",tone=st.delta<0?" down":st.delta>0?" up":"";const recent=st.entries.slice(-4).reverse().map(x=>`${new Date(x.at).toLocaleDateString("ru-RU",{day:"2-digit",month:"2-digit"})} · ${money(x.total)}`).join(" · ");return `<div class="td-saved-basket-history${tone}"><b>Сейчас ${money(latest)}</b> · было ${money(st.first.total)} · ${sign}${money(Math.abs(st.delta))}${st.deltaPct?` (${st.deltaPct>0?"+":""}${st.deltaPct}%)`:""}<small>${esc(recent)}</small></div>`}
  function save(name){const s=window.TDShoppingState?.get?.(),plan=s?.lastPlans?.[0];if(!s||!plan?.products?.length)return{ok:false,message:"Сначала собери корзину."};const rows=read(),title=String(name||suggestedName()).trim().slice(0,50)||"Моя корзина";const row={id:"basket_"+Date.now(),name:title,createdAt:new Date().toISOString(),snapshot:currentSnapshot(),productNames:plan.products.slice(0,6).map(x=>x.name),productCount:plan.products.length,total:Number(plan.total)||0,mode:s.mode||"multi"};rows.unshift(row);write(rows);const h=window.TDBasketPriceHistory;h?.record?.({basketId:row.id,name:row.name,signature:h.signature(row.snapshot,plan.products),total:row.total,at:row.createdAt,source:"saved"});return{ok:true,row,message:`Сохранил «${title}».`}}
  function remove(id){const rows=read(),next=rows.filter(x=>x.id!==id);write(next);window.TDBasketPriceHistory?.removeBasket?.(id);return next.length!==rows.length}
  function apply(id){const row=read().find(x=>x.id===id);if(!row?.snapshot||!window.TDShoppingState||!window.TDShoppingOptimizer)return{ok:false,message:"Не получилось открыть сохранённую корзину."};try{TDShoppingState.commit("RESTORE_SAVED_BASKET",s=>{for(const k of FIELDS)if(Object.prototype.hasOwnProperty.call(row.snapshot,k))s[k]=clone(row.snapshot[k]);const plans=TDShoppingOptimizer.optimize(s)||[],best=plans[0];if(!best?.products)throw new Error("no plan");s.products=best.products;s.currentTotal=best.total;s.lastPlans=plans;},`Повторить «${row.name}»`);TDShoppingState.syncCart?.();window.TDBasketPriceHistory?.recordCurrent?.({basketId:row.id,name:row.name,source:"repeat"});window.TDBaiCheckout?.refresh?.();window.dispatchEvent(new CustomEvent("td:saved-basket-applied",{detail:{id:row.id,name:row.name,total:TDShoppingState.get().currentTotal}}));return{ok:true,row,message:`Корзина «${row.name}» собрана заново по текущим ценам.`}}catch(e){console.warn("[Saved Baskets] apply failed",e);return{ok:false,message:"Не получилось пересобрать эту корзину."}}}
  function ensureCss(){if(document.getElementById("td-saved-baskets-style"))return;const s=document.createElement("style");s.id="td-saved-baskets-style";s.textContent=`.td-saved-baskets-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.td-saved-baskets-head button,.td-saved-basket-actions button,.td-save-basket-btn{border:0;border-radius:12px;padding:10px 12px;font:800 11px Manrope,sans-serif}.td-saved-baskets-head button,.td-save-basket-btn{background:#161410;color:#fff}.td-saved-basket{border-top:1px solid #eee8de;padding:12px 0}.td-saved-basket:first-of-type{border-top:0}.td-saved-basket-title{display:flex;justify-content:space-between;gap:10px}.td-saved-basket-title b{font-size:13px}.td-saved-basket-meta{font-size:10px;color:#6b6458;font-weight:700;margin:4px 0 8px;line-height:1.4}.td-saved-basket-history{font-size:10px;font-weight:800;line-height:1.4;background:#f4f1ea;border-radius:10px;padding:8px 9px;margin:7px 0}.td-saved-basket-history.down{background:#e7f6ec;color:#0f7b4a}.td-saved-basket-history.up{background:#fff3dd;color:#8a5a00}.td-saved-basket-history small{display:block;margin-top:3px;font-size:9px;font-weight:700;opacity:.78}.td-saved-basket-actions{display:flex;gap:7px}.td-saved-basket-actions [data-repeat]{background:#e7f6ec;color:#0f7b4a;flex:1}.td-saved-basket-actions [data-delete]{background:#f4f1ea;color:#6b6458}.td-save-basket-btn{width:100%;margin-top:8px;background:#fff;color:#161410;border:1px solid #e6dfd3}`;document.head.appendChild(s)}
  function basketPage(){const account=document.querySelector(".td-account"),pages=account?.querySelectorAll(".td-account-page");return pages?.[2]||null}
  function renderAccount(){ensureCss();const page=basketPage();if(!page)return;const rows=read();page.innerHTML=`<div class="td-account-card"><div class="td-saved-baskets-head"><div><h3>Мои корзины</h3><div class="td-account-muted">До ${MAX} наборов. Повторяем корзину по текущим ценам и запоминаем, как менялась её полная стоимость.</div></div><button type="button" data-save-current>+ Сохранить</button></div>${rows.map(x=>`<div class="td-saved-basket"><div class="td-saved-basket-title"><b>${esc(x.name)}</b><strong>${money(window.TDBasketPriceHistory?.stats?.(x.id)?.latest?.total??x.total)}</strong></div><div class="td-saved-basket-meta">${esc((x.productNames||[]).join(", "))}${x.productCount>(x.productNames||[]).length?` · ещё ${x.productCount-(x.productNames||[]).length}`:""}<br>сохранена ${esc(new Date(x.createdAt).toLocaleDateString("ru-RU"))}</div>${historyHtml(x)}<div class="td-saved-basket-actions"><button type="button" data-repeat="${esc(x.id)}">Повторить покупку</button><button type="button" data-delete="${esc(x.id)}" aria-label="Удалить корзину">Удалить</button></div></div>`).join("")||'<div class="td-account-placeholder">Сохрани первую корзину — потом её можно будет пересобрать одним нажатием и видеть историю общей цены.</div>'}</div>`;page.querySelector("[data-save-current]")?.addEventListener("click",()=>{if(read().length>=MAX){alert(`Можно сохранить до ${MAX} корзин. Удали одну старую.`);return}const name=prompt("Название корзины",suggestedName());if(name===null)return;const r=save(name);if(!r.ok)alert(r.message);renderAccount()});page.querySelectorAll("[data-repeat]").forEach(b=>b.onclick=()=>{const r=apply(b.dataset.repeat);if(r.ok){window.TDAccountHub?.close?.();setTimeout(()=>window.TDBai?.openPanel?.(),80)}else alert(r.message)});page.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>{if(confirm("Удалить сохранённую корзину и её историю цены?")){remove(b.dataset.delete);renderAccount()}})}
  function decorateCheckout(){ensureCss();document.querySelectorAll(".td-ai-checkout").forEach(card=>{if(card.querySelector("[data-save-basket]"))return;const note=card.querySelector(".td-ai-checkout-note"),btn=document.createElement("button");btn.type="button";btn.className="td-save-basket-btn";btn.dataset.saveBasket="1";btn.textContent="Сохранить эту корзину";btn.onclick=()=>{if(read().length>=MAX){window.TDAccountHub?.open?.(2);return}const name=prompt("Название корзины",suggestedName());if(name===null)return;const r=save(name);const status=card.querySelector("[data-bai-checkout-status]");if(status){status.hidden=false;status.textContent=r.message}if(!r.ok)return};note?.insertAdjacentElement("beforebegin",btn)})}
  const obs=new MutationObserver(()=>decorateCheckout());function boot(){ensureCss();decorateCheckout();obs.observe(document.body,{childList:true,subtree:true})}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();window.addEventListener("td:account-opened",()=>requestAnimationFrame(renderAccount));window.addEventListener("td:saved-baskets",()=>{if(document.querySelector(".td-account"))renderAccount()});window.addEventListener("td:basket-price-history",()=>{if(document.querySelector(".td-account"))renderAccount()});
  window.TDSavedBaskets={list:()=>clone(read()),save,remove,apply,renderAccount};
})();