import fs from 'node:fs';
import path from 'node:path';
import {applyReviewDecisions} from '../review-decision.mjs';
import {renderSftJsonl} from './prepare-sft.mjs';
const root=new URL('../',import.meta.url),registry=JSON.parse(fs.readFileSync(new URL('sources.json',root),'utf8'));
const jl=f=>fs.readFileSync(f,'utf8').split(/\r?\n/).filter(Boolean).map(JSON.parse);
const [dir,decisions,out]=process.argv.slice(2); if(!dir||!decisions||!out)throw Error('usage: review-export REVIEW_DIR DECISIONS OUT_DIR');
const left=jl(path.join(dir,'left-candidates.jsonl')),right=jl(path.join(dir,'right-candidates.jsonl')),queue=JSON.parse(fs.readFileSync(path.join(dir,'review-queue.json'),'utf8'));
const result=applyReviewDecisions({left,right,queue,decisions:jl(decisions),registry}); fs.mkdirSync(out,{recursive:true});
fs.writeFileSync(path.join(out,'gold.jsonl'),result.approved.map(JSON.stringify).join('\n')+(result.approved.length?'\n':''));
fs.writeFileSync(path.join(out,'sft.jsonl'),renderSftJsonl(result.approved,registry));
fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify(result.summary,null,2)+'\n'); console.log(JSON.stringify(result.summary));
