import fs from 'node:fs';
import assert from 'node:assert/strict';
import {buildCorpus} from './corpus-builder.mjs';
import {importTeacherResults,buildReviewQueue,candidatePrediction,structuredHash} from './candidate-import.mjs';
import {trainingEligibility} from './firewall.mjs';

const here=new URL('./',import.meta.url);
const read=name=>JSON.parse(fs.readFileSync(new URL(name,here),'utf8'));
const registry=read('sources.json');
const profile=read('profiles/deepseek-r1-distill-qwen-7b.json');
const tasks=buildCorpus(),first=tasks[0];
const base=(task,output)=>({task_id:task.id,profile_id:profile.id,model:profile.model,revision:profile.revision,prompt_version:'test-v1',prompt_sha256:'a'.repeat(64),output_sha256:structuredHash(output),runtime_fingerprint:'b'.repeat(64),generation:{temperature:0.2,max_tokens:100},output});
const good=base(first,{intent:'build_basket',hard_constraints:{budget_max:2500},soft_preferences:{price:'balanced'},shopping_plan:{categories:['protein','base','fruit']},actions:[{type:'CHANGE_BUDGET',value:2500}],critic:{pass:true,issues:[]},confidence:{overall:'high',price:'verified',availability:'verified',quality:'verified'}});
const badReasoning=base(tasks[1],{intent:'build_basket',reasoning:'raw notes',hard_constraints:{},soft_preferences:{},shopping_plan:{},actions:[],critic:{pass:true,issues:[]},confidence:{overall:'high'}});
const wrongProfile={...base(tasks[2],{intent:'build_basket'}),profile_id:'other'};
const wrongRevision={...base(tasks[3],{intent:'build_basket'}),revision:'0'.repeat(40)};
const badHash={...base(tasks[4],{intent:'build_basket'}),output_sha256:'c'.repeat(63)};
const result=importTeacherResults({rows:[good,badReasoning,wrongProfile,wrongRevision,badHash],tasks,profile,registry});
assert.equal(result.candidates.length,1);
assert.equal(result.rejected.length,4);
assert.ok(result.rejected.some(x=>x.reason==='revision_mismatch'));
assert.ok(result.rejected.some(x=>x.reason==='invalid_output_hash'));
const candidate=result.candidates[0];
assert.equal(candidate.review.status,'candidate');
assert.equal(candidate.target.confidence.price,'unknown');
assert.equal(candidate.target.confidence.availability,'unknown');
assert.equal(candidate.target.confidence.quality,'unknown');
assert.equal(candidate.provenance.sources[0].revision,profile.revision);
assert.equal(candidate.provenance.sources[0].prompt_sha256,good.prompt_sha256);
assert.equal(candidate.provenance.sources[0].output_sha256,structuredHash(good.output));
assert.equal(candidate.provenance.sources[0].producer_output_sha256,good.output_sha256);
assert.equal(candidate.provenance.sources[0].runtime_fingerprint,good.runtime_fingerprint);
assert.equal(trainingEligibility(candidate,registry).eligible,false,'candidate must not be trainable before review');
const approved=JSON.parse(JSON.stringify(candidate));approved.review.status='approved';
assert.equal(trainingEligibility(approved,registry).eligible,true,'approved candidate from training_allowed source may enter export');
const queue=buildReviewQueue([candidate]);
assert.equal(queue.length,1);
assert.equal(queue[0].priority,'normal');
assert.equal(candidatePrediction(candidate).id,first.id);
const blocked={...profile,source_id:'yandex_foundation_models_api'};
assert.throws(()=>importTeacherResults({rows:[good],tasks,profile:blocked,registry}));
console.log('Bai teacher candidate import smoke passed');
