import fs from 'node:fs';
import assert from 'node:assert/strict';
import {buildCorpus} from './corpus-builder.mjs';
import {importTeacherResults,buildReviewQueue,candidatePrediction} from './candidate-import.mjs';
import {trainingEligibility} from './firewall.mjs';

const here=new URL('./',import.meta.url);
const read=name=>JSON.parse(fs.readFileSync(new URL(name,here),'utf8'));
const registry=read('sources.json');
const profile=read('profiles/deepseek-r1-distill-qwen-7b.json');
const tasks=buildCorpus(),first=tasks[0];
const good={task_id:first.id,profile_id:profile.id,output:{intent:'build_basket',hard_constraints:{budget_max:2500},soft_preferences:{price:'balanced'},shopping_plan:{categories:['protein','base','fruit']},actions:[{type:'CHANGE_BUDGET',value:2500}],critic:{pass:true,issues:[]},confidence:{overall:'high',price:'verified',availability:'verified',quality:'verified'}}};
const badReasoning={task_id:tasks[1].id,profile_id:profile.id,output:{intent:'build_basket',reasoning:'raw notes',hard_constraints:{},soft_preferences:{},shopping_plan:{},actions:[],critic:{pass:true,issues:[]},confidence:{overall:'high'}}};
const wrongProfile={task_id:tasks[2].id,profile_id:'other',output:{intent:'build_basket'}};
const result=importTeacherResults({rows:[good,badReasoning,wrongProfile],tasks,profile,registry});
assert.equal(result.candidates.length,1);
assert.equal(result.rejected.length,2);
const candidate=result.candidates[0];
assert.equal(candidate.review.status,'candidate');
assert.equal(candidate.target.confidence.price,'unknown');
assert.equal(candidate.target.confidence.availability,'unknown');
assert.equal(candidate.target.confidence.quality,'unknown');
assert.equal(trainingEligibility(candidate,registry).eligible,false,'candidate must not be trainable before review');
const approved=JSON.parse(JSON.stringify(candidate));approved.review.status='approved';
assert.equal(trainingEligibility(approved,registry).eligible,true,'approved candidate from training_allowed source may enter export');
const queue=buildReviewQueue([candidate]);
assert.equal(queue.length,1);
assert.equal(queue[0].priority,'normal');
assert.equal(candidatePrediction(candidate).id,first.id);
const blocked={...profile,source_id:'yandex_foundation_models_api'};
assert.throws(()=>importTeacherResults({rows:[good],tasks,profile:blocked,registry}));
console.log('Bai teacher candidate import smoke passed');
