import assert from "node:assert/strict";
import fs from "node:fs";

const html=fs.readFileSync("index.html","utf8"),ui=fs.readFileSync("v2-shell.js","utf8"),css=fs.readFileSync("v2-shell.css","utf8"),cinema=fs.readFileSync("v2-cinematic.css","utf8"),bai=fs.readFileSync("bai-assistant.js","utf8");
const historyUi=fs.readFileSync("price-history.js","utf8"),substitutions=fs.readFileSync("smart-substitutions.js","utf8");
const app=fs.readFileSync("app.js","utf8");
const polish=fs.readFileSync("v2-polish.js","utf8"),mobileDock=fs.readFileSync("v2-mobile-dock.js","utf8"),life=fs.readFileSync("bai-life.js","utf8");
const cards=fs.readFileSync("cards.css","utf8"),brand=fs.readFileSync("brand-votonobay-v1.js","utf8"),brandCss=fs.readFileSync("votonobay-brand-v1.css","utf8"),manifest=JSON.parse(fs.readFileSync("manifest.json","utf8"));
const bayFirst=fs.readFileSync("votonobay-bay-first-v3.js","utf8"),bayFirstCss=fs.readFileSync("votonobay-bay-first-v3.css","utf8");
new Function(bayFirst);
assert.match(html,/v2-shell\.css\?v=/);assert.match(html,/v2-shell\.js\?v=/);
assert.match(html,/v2-cinematic\.css\?v=/);assert.match(html,/v2-polish\.js\?v=/);
for(const component of ["Header","HeroSearch","StoreStrip","ProductGrid","ProductCard","ShoppingList","Footer","MobileDock"])assert.match(ui,new RegExp(`function ${component}\\(`));
for(const action of ["tdV2Search","tdV2Quick","tdV2Menu","tdV2About"])assert.match(ui,new RegExp(`window\\.${action}`));
assert.match(css,/@media\(max-width:700px\)/);assert.match(css,/grid-template-columns:minmax\(0,1fr\) 310px/);
assert.match(css,/\.phone\{max-width:none!important\}/);
assert.match(cinema,/--v2-canvas:#06110c/);assert.match(cinema,/\.v2-hero-bai/);assert.match(cinema,/\.v2-bottom-nav/);
assert.match(cinema,/body \.td-account/);assert.match(cinema,/grid-template-columns:60px minmax\(0,1fr\) auto/);
assert.match(life,/micro-blink/);assert.match(html,/bai-life\.js\?v=/);
assert.match(mobileDock,/Мобильная навигация/);assert.match(html,/v2-mobile-dock\.js\?v=/);
assert.match(mobileDock,/document\.querySelectorAll\("\.v2-bottom-nav"\)/);assert.match(mobileDock,/dock!==nav\)dock\.remove\(\)/);
assert.match(mobileDock,/aria-current/);assert.match(mobileDock,/type="button"/);
assert.doesNotMatch(mobileDock,/MutationObserver/);
assert.match(ui,/≈ — ориентир, подтверждённые цены отмечаем отдельно/);assert.match(ui,/Помогаем понять, как лучше собрать корзину/);
assert.match(ui,/Votonobay — на главную/);assert.match(ui,/Покупки\. <em>Как лучше\.<\/em>/);assert.match(ui,/Сравнить варианты/);
assert.match(brand,/const BRAND="Votonobay"/);assert.match(brandCss,/body\.td-votonobay/);assert.doesNotMatch(brand,/td-ai-|TDBai|bai-/);
for(const state of ["idle","greeting","peek","curious","checking","thinking","suspicious","happy","excited","big-saving","confused","scared","playful","sleepy","sleeping","hidden","goodbye"])assert.match(bai,new RegExp(`["']?${state}["']?\\s*:`));
assert.doesNotMatch(bai,/MutationObserver/);assert.match(bai,/Уложить Бая спать/);assert.match(bai,/bai-tail-peek\.webp/);
assert.match(historyUi,/tdHistorySignature/);assert.match(substitutions,/dataset\.signature/);
assert.match(app,/function comparisonLead\(/);assert.match(app,/Победителя пока нет/);assert.match(app,/ЛУЧШИЙ ПОДТВЕРЖДЁННЫЙ ВАРИАНТ/);
assert.match(app,/class="brand-home" onclick="go\('home'\)"/);
assert.equal(manifest.name,"Votonobay");assert.equal(manifest.short_name,"Votonobay");assert.equal(manifest.theme_color,"#102018");assert.equal(manifest.lang,"ru");assert.equal(manifest.scope,"./");
assert.match(cards,/\.sku-plate img\{[^}]*object-fit:contain/);assert.match(cards,/\.thumb img,\.product-packaging img\{[^}]*object-fit:contain/);

// Bay-first V3: Bay is the primary decision path, self-service remains available.
assert.match(brand,/votonobay-bay-first-v3\.js/);
assert.match(bayFirst,/Спросить Бая/);assert.match(bayFirst,/Искать самому/);assert.match(bayFirst,/Что лучше выбрать\?/);
assert.match(bayFirst,/window\.TDShoppingAssistant\?\.open/);assert.match(bayFirst,/window\.tdBayFirstAsk/);
assert.match(bayFirstCss,/--bay3-bg:#050a07/);assert.match(bayFirstCss,/\.v2-bay-primary/);assert.match(bayFirstCss,/@media\(min-width:821px\)\{\.td-ai/);
assert.match(bai,/window\.TDShoppingAssistant\?\.open/);assert.match(bai,/[Цц]ена, удобство и время/);assert.doesNotMatch(bai,/Я Бай\. Чую, где дешевле/);
console.log("V2 UI contract passed: responsive Votonobay shell, Bay-first decision entry, self-service fallback, honest data labels, correct PWA identity and accessible navigation are wired.");
